export const CARTOONMOJI_QUESTIONS = {
  easy: [
    { emoji: "🦁 👑 🐯", answer: "The Lion King" },
    { emoji: "🧽 🍍 🌊", answer: "SpongeBob SquarePants" },
    { emoji: "🐭 🧀 🏰", answer: "Mickey Mouse" },
    { emoji: "🐶 🚨 🏙", answer: "Paw Patrol" },
    { emoji: "🤠 🚀 👦", answer: "Toy Story" },
    { emoji: "🐉 👦 🔥", answer: "How to Train Your Dragon" },
    { emoji: "🐼 🥋 👊", answer: "Kung Fu Panda" },
    { emoji: "🧸 ❤️ 🍯", answer: "Winnie the Pooh" },
    { emoji: "🥕 🐰 🎯", answer: "Bugs Bunny" },
    { emoji: "🐢 🥷 🍕", answer: "Teenage Mutant Ninja Turtles" },
    { emoji: "🤖 🚗 ⚡", answer: "Transformers" },
    { emoji: "👨🔧 🚗 🔧", answer: "Handy Manny" },
    { emoji: "👧 👸 ❄", answer: "Frozen" },
    { emoji: "👦 ⚡ 🦸", answer: "Ben 10" },
    { emoji: "🧙 📜 ⭐", answer: "Harry Potter" },
  ],

  medium: [
    { emoji: "🐭 🍞 🧀", answer: "Jerry" },
    { emoji: "🐱 🏃 💥", answer: "Tom" },
    { emoji: "🐶 🕵️‍♂️ 🧪", answer: "Scooby-Doo" },
    { emoji: "🧒 🟦 🔬", answer: "Jimmy Neutron" },
    { emoji: "🦍 💪 😂", answer: "Donkey Kong" },
    { emoji: "🦎 🦸‍♂️ 🌙", answer: "Gekko" },
    { emoji: "🦋 👧 🌈", answer: "Miraculous Ladybug" },
    { emoji: "🦆 💸 🏦", answer: "Scrooge McDuck" },
    { emoji: "🐦 🏹 🎯", answer: "Hawkeye" },
    { emoji: "👦 🛹 🔥", answer: "Kick Buttowski" },
    { emoji: "🐷 👑 🏰", answer: "Peppa Pig" },
    { emoji: "🧙‍♂️ ⭐ 🎩", answer: "Mickey Wizard (Fantasia)" },
    { emoji: "🐵 😂 🍌", answer: "George (Curious George)" },
    { emoji: "👧 🧪 🌋", answer: "Doc McStuffins" },
    { emoji: "🐜 💪 🤏", answer: "Atom Ant" },
  ],

  hard: [
    { emoji: "🦊 🌪️ 🧠", answer: "Tails" },
    { emoji: "🦔 ⚡ 🏎️", answer: "Sonic" },
    { emoji: "🐉 📘 💨", answer: "Jake Long" },
    { emoji: "🧛‍♂️ 😎 🎸", answer: "Marceline" },
    { emoji: "👦 ⏳ 🕒", answer: "Timmy Turner" },
    { emoji: "🐱 🐾 🎤", answer: "Hello Kitty" },
    { emoji: "🦍 🎧 🔊", answer: "Beast Boy" },
    { emoji: "🧙‍♀️ 🐈 🌙", answer: "Luz" },
    { emoji: "🦆 🚀 🛡️", answer: "Darkwing Duck" },
    { emoji: "🐭 🔬 👨‍🔬", answer: "Pinky" },
    { emoji: "🐀 🧠 👨‍🔬", answer: "The Brain" },
    { emoji: "🐈‍⬛ 🌙 🔮", answer: "Salem" },
    { emoji: "🔫 🤖 👦", answer: "Astro Boy" },
    { emoji: "🐦🌌 🗡️", answer: "Falcon" },
    { emoji: "👾 💻 🤖", answer: "Reboot" },
  ],
};

