import { UserStatusInterface } from "../../types";

export const STATUSES: UserStatusInterface[] = [
  {
    id: "1",
    url: "/background/Frame_937-removebg-preview.png",
    status: "unwatched",
    username: "Sam Wilson",
    userProfilePicture:
      "/assets/adda/profilePictures/pexels-justin-shaifer-501272-1222271.jpg",
    createdAt: "",
    type: "image",
    userId: "12345",
    viewCount: 30,
  },
  {
    id: "2",
    url: "/video/addiction/We_know_THE_STRUGGLES.mp4",
    status: "watched",
    username: "Sita",
    userProfilePicture: "/assets/adda/profilePictures/pexels-olly-733872.jpg",
    createdAt: "",
    type: "video",
    userId: "67890",
    viewCount: 20,
  },
  {
    id: "3",
    url: "https://www.w3schools.com/html/mov_bbb.mp4",
    status: "unwatched",
    username: "Vishnu",
    userProfilePicture:
      "/assets/adda/profilePictures/pexels-simon-robben-55958-614810.jpg",
    createdAt: "",
    type: "video",
    userId: "23456",
    viewCount: 15,
  },
  {
    id: "4",
    url: "https://www.w3schools.com/html/movie.mp4",
    status: "watched",
    username: "Xavier",
    userProfilePicture:
      "/assets/adda/profilePictures/pexels-stefanstefancik-91227.jpg",
    createdAt: "",
    type: "video",
    userId: "34567",
    viewCount: 25,
  },
  {
    id: "5",
    url: "https://samplelib.com/lib/preview/mp4/sample-5s.mp4",
    status: "watched",
    username: "Zabeen",
    userProfilePicture:
      "/assets/adda/profilePictures/pexels-stefanstefancik-91227.jpg",
    createdAt: "",
    type: "video",
    userId: "45678",
    viewCount: 18,
  },
  {
    id: "6",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4",
    status: "watched",
    username: "Rahul",
    userProfilePicture:
      "/assets/adda/profilePictures/pexels-stefanstefancik-91227.jpg",
    createdAt: "",
    type: "video",
    userId: "56789",
    viewCount: 22,
  },
  {
    id: "7",
    url: "https://www.w3schools.com/html/mov_bbb.mp4",
    status: "watched",
    username: "Rahul",
    userProfilePicture:
      "/assets/adda/profilePictures/pexels-stefanstefancik-91227.jpg",
    createdAt: "",
    type: "video",
    userId: "56789",
    viewCount: 22,
  },
  {
    id: "8",
    url: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
    status: "unwatched",
    username: "Rajesh",
    userProfilePicture:
      "/assets/adda/profilePictures/pexels-justin-shaifer-501272-1222271.jpg",
    createdAt: "",
    type: "video",
    userId: "67891",
    viewCount: 28,
  },
  {
    id: "9",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4",
    status: "watched",
    username: "Rahul",
    userProfilePicture:
      "/assets/adda/profilePictures/pexels-stefanstefancik-91227.jpg",
    createdAt: "",
    type: "video",
    userId: "56789",
    viewCount: 22,
  },
  {
    id: "10",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4",
    status: "watched",
    username: "Rahul",
    userProfilePicture:
      "/assets/adda/profilePictures/pexels-stefanstefancik-91227.jpg",
    createdAt: "",
    type: "video",
    userId: "56789",
    viewCount: 22,
  },
  {
    id: "10",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4",
    status: "watched",
    username: "Rahul",
    userProfilePicture:
      "/assets/adda/profilePictures/pexels-stefanstefancik-91227.jpg",
    createdAt: "",
    type: "video",
    userId: "56789",
    viewCount: 22,
  },
  {
    id: "10",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4",
    status: "watched",
    username: "Rahul",
    userProfilePicture:
      "/assets/adda/profilePictures/pexels-stefanstefancik-91227.jpg",
    createdAt: "",
    type: "video",
    userId: "56789",
    viewCount: 22,
  },
  {
    id: "10",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4",
    status: "watched",
    username: "Rahul",
    userProfilePicture:
      "/assets/adda/profilePictures/pexels-stefanstefancik-91227.jpg",
    createdAt: "",
    type: "video",
    userId: "56789",
    viewCount: 22,
  },
  {
    id: "10",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4",
    status: "watched",
    username: "Rahul",
    userProfilePicture:
      "/assets/adda/profilePictures/pexels-stefanstefancik-91227.jpg",
    createdAt: "",
    type: "video",
    userId: "56789",
    viewCount: 22,
  },
  {
    id: "10",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4",
    status: "watched",
    username: "Rahul",
    userProfilePicture:
      "/assets/adda/profilePictures/pexels-stefanstefancik-91227.jpg",
    createdAt: "",
    type: "video",
    userId: "56789",
    viewCount: 22,
  },
  {
    id: "10",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4",
    status: "watched",
    username: "Rahul",
    userProfilePicture:
      "/assets/adda/profilePictures/pexels-stefanstefancik-91227.jpg",
    createdAt: "",
    type: "video",
    userId: "56789",
    viewCount: 22,
  },
];
