export const getItemEmoji = (item: string): string => {
  const normalizedItem = item.toUpperCase(); // Normalize to uppercase
  const emojis: Record<string, string> = {
    // Social Media puzzle emojis (Easy)
    CHAT: "💬",
    LIKE: "👍",
    TAG: "🏷️",
    APP: "📱",
    POST: "📝",
    BIO: "🧑‍💼",
    DM: "✉️",
    VIEW: "👁️",
    // Social Media puzzle emojis (Medium)
    COMMENT: "💭",
    SNAP: "📸",
    REPOST: "🔁",
    PROFILE: "👤",
    FOLLOW: "➡️",
    TRENDS: "📈",
    STATUS: "📊",
    REACT: "😊",
    // Social Media puzzle emojis (Hard)
    INFLUENCER: "🌟",
    ALGORITHM: "⚙️",
    ENGAGEMENT: "🤝",
    SCHEDULING: "🕒",
    MONETIZED: "💰",
    SUBSCRIBERS: "👥",
    DISCOVERED: "🔍",
    COMMENTING: "💬",
    // Career puzzle emojis (Easy)
    CHEF: "👨‍🍳",
    GUARD: "🛡️",
    CLERK: "📋",
    NURSE: "👩‍⚕️",
    DRIVER: "🚗",
    WAITER: "🍽️",
    JANITOR: "🧹",
    ACTOR: "🎭",
    // Career puzzle emojis (Medium)
    TEACHER: "👩‍🏫",
    DENTIST: "🦷",
    WRITER: "✍️",
    BANKER: "💸",
    MECHANIC: "🔧",
    ENGINEER: "⚙️",
    FIREMAN: "👨‍🚒",
    DESIGNER: "🎨",
    // Career puzzle emojis (Hard)
    PHARMACIST: "💊",
    DATAENGINEER: "💾",
    NEUROLOGIST: "🧠",
    CYBERLAWYER: "⚖️",
    ANALYST: "📉",
    ARCHITECT: "🏛️",
    SCIENTIST: "🔬",
    STRATEGIST: "📈",
    // Icons puzzle emojis (Easy)
    HOME: "🏠",
    MAIL: "✉️",
    SAVE: "💾",
    CALL: "📞",
    LOCK: "🔒",
    EXIT: "🚪",
    HELP: "❓",
    // Icons puzzle emojis (Medium)
    UPLOAD: "⬆️",
    CAMERA: "📷",
    NOTIFY: "🔔",
    REFRESH: "🔄",
    SEARCH: "🔍",
    FILTER: "🔎",
    RECORD: "🎥",
    DELETE: "🗑️",
    // Icons puzzle emojis (Hard)
    DASHBOARD: "📊",
    CALENDAR: "📅",
    TOOLBAR: "🛠️",
    MULTITASK: "🖥️",
    SIDEPANEL: "📑",
    SETTINGS: "⚙️",
    WIDGETS: "🧩",
    NAVIGATOR: "🧭",
  };
  return emojis[normalizedItem] || "✨";
};
