import { PsychologistWorkshop } from "@/types/employee/psychologistWorkshopTypes";

export const PSYCHOLOGIST_WOKSHOPS: PsychologistWorkshop[] = [
  {
    _id: "1",
    psychologist: "jasim",
    workshop: "Buddy Camp",
    // title: "Music Therapy",
    duration: "6 Months",
    ageCategory: "6-12",
    status: "Ongoing",
    startDate: "01-01-2026",
    endDate: "01-06-2026",
    totalSessions: 20,
    completedSession: 2,
    coverImage: "/assets/workshopv2/buddycamp/buddy-camp-logo.png",
    candidates: [
      {
        name: "name 1",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 2",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 3",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 4",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 5",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 6",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 7",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 8",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 9",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 10",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
    ],
  },
  {
    _id: "2",
    psychologist: "jasim",
    workshop: "Teen Camp",
    // title: "Story Telling Therapy",
    ageCategory: "13-19",
    duration: "3 Months",
    status: "Completed",
    startDate: "15-10-2025",
    endDate: "15-01-2026",
    totalSessions: 12,
    completedSession: 12,
    coverImage: "/assets/workshopv2/teencamp/teen-camp-logo.png",
    candidates: [
      {
        name: "name 1",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 2",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 3",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 4",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 5",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 6",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 7",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 8",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
    ],
  },
  {
    _id: "3",
    psychologist: "jasim",
    workshop: "Buddy Camp",
    // title: "Art Therapy",
    ageCategory: "6-12",
    status: "Upcoming",
    duration: "1 Month",
    startDate: "05-02-2026",
    endDate: "05-03-2026",
    totalSessions: 8,
    completedSession: 0,
    coverImage: "/assets/workshopv2/buddycamp/buddy-camp-logo.png",
    candidates: [
      {
        name: "name 1",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 2",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 3",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 4",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 5",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 6",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 7",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
      {
        name: "name 8",
        age: 10,
        fatherName: "Father",
        motherName: "Mother",
        mobileNumber: 9876543210,
        address: "Addressss",
        dateOfBirth: "01-01-2016",
        gender: "Male",
        class: 4,
        school: "Ghss Kerala",
      },
    ],
  },
];
