import { Slide } from "@/types";

export const SLIDES: Slide[] = [
  {
    id: 1,
    img: "/assets/home/newPage/bg/banner/plan banner.png",
    tag: "⚡ LIMITED OFFER",
    headline: "3 Day Trial",
    highlightWord: "Trial",
    sub: "Try everything free for 3 days — full access with zero hassle.",
    cta: "Browse Plans",
    accent: "#a8ff78",
    bg: "from-[#071a0e] via-[#0f2e1a] to-[#1a4a2e]",
    shape: "circle",
    emoji: "🎯",
    badges: ["✓ Full Access", "✓ Zero Risk"],
    link: "/membership",
    items: [
      {
        name: "Explore Membership",
        link: "/membership",
        color: "#a8ff78",
      },
    ],
  },
  // {
  //   id: 2,
  //   img: "/assets/home/newPage/bg/banner/workshop banner.png",
  //   tag: "🎓 WORKSHOPS",
  //   headline: "Workshops",
  //   highlightWord: "Workshops",
  //   sub: "Workshops for ages 6–12 with hands-on play-based learning, and ages 13–19 with advanced, expert-led sessions.",
  //   cta: "Explore Workshops",
  //   accent: "#f9c74f",
  //   bg: "from-[#0a0a1e] via-[#1a1a2e] to-[#16213e]",
  //   shape: "triangle",
  //   emoji: "🧠",
  //   badges: ["Ages 6–12", "Ages 13–19", "Expert Led", "Live Sessions"],
  //   link: "/mentoons-workshops",
  //   items: [
  //     {
  //       name: "Instant Buddy",
  //       link: "/mentoons-workshops",
  //       color: "#f9c74f",
  //     },
  //     {
  //       name: "Quarter Buddy",
  //       link: "/mentoons-workshops",
  //       color: "#f4845f",
  //     },
  //     {
  //       name: "Buddy 6",
  //       link: "/mentoons-workshops",
  //       color: "#43c59e",
  //     },
  //     {
  //       name: "Buddy 12",
  //       link: "/mentoons-workshops",
  //       color: "#7b68ee",
  //     },
  //   ],
  // },
  {
    id: 3,
    img: "/assets/home/newPage/bg/banner/Products banner.png",
    tag: "🛍️ PRODUCTS",
    headline: "Products",
    highlightWord: "Products",
    sub: "Products built for kids, teens, adults and parents — designed around how each age group thinks, plays, and grows.",
    cta: "Shop by Age",
    accent: "#ff9f43",
    bg: "from-[#1a0505] via-[#2e0f0f] to-[#4a1a1a]",
    shape: "star",
    emoji: "🚀",
    badges: ["Kids", "Teens", "Adults", "Parents"],
    link: "/products",
    items: [
      {
        name: "Conversation Starter Cards",
        link: "/products?productType=mentoons%20cards&cardType=conversation%20starter%20cards#product",
        image: "/assets/home/newPage/csc.png",
      },
      {
        name: "Story Re-Teller Cards",
        link: "/products?productType=mentoons%20cards&cardType=story%20re-teller%20card#product",
        image: "/assets/home/newPage/Src.png",
      },
      {
        name: "Silent Stories",
        link: "/products?productType=mentoons%20cards&cardType=silent%20stories#product",
        image: "/assets/home/newPage/ST.png",
      },
      {
        name: "Conversation Story Cards",
        link: "/products?productType=mentoons%20cards&cardType=conversation%20story%20cards#products",
        image:
          "https://mentoons-products.s3.ap-northeast-1.amazonaws.com/Products/Conversation_Story_Cards_20%2B/Conversation+Story+Cards+20%2B.png",
      },
      {
        name: "Coloring Books",
        link: "/products?productType=mentoons_coloring_book#product",
        image: "/assets/home/newPage/coloring book.png",
      },
      {
        name: "Journals",
        link: "/products",
        image: "/assets/home/newPage/journals.png",
      },
    ],
  },
  {
    id: 4,
    img: "/assets/home/newPage/bg/banner/podcast banner.png",
    tag: "🎧 PODCASTS",
    headline: "Podcasts",
    highlightWord: "Podcasts",
    sub: "Engaging audio stories, expert talks, and insightful discussions designed to inspire kids, teens, and parents.",
    cta: "Listen Now",
    accent: "#6dd5ed",
    bg: "from-[#04141c] via-[#0b2b3a] to-[#124559]",
    shape: "wave",
    emoji: "🎙️",
    badges: ["Storytelling", "Expert Talks", "Learning Audio"],
    link: "/mentoons-podcast",
    items: [
      {
        name: "Mobile Addiction",
        link: "/mentoons-podcast",
        color: "#e040fb",
      },
      {
        name: "Gaming Addiction",
        link: "/mentoons-podcast",
        color: "#ff6f00",
      },
      {
        name: "Teen Emotions",
        link: "/mentoons-podcast",
        color: "#00e676",
      },
    ],
  },
  {
    id: 5,
    img: "/assets/home/newPage/bg/banner/comic banner.png",
    tag: "📚 COMICS",
    headline: "Comics",
    highlightWord: "Comics",
    sub: "Fun, meaningful comic stories that teach life lessons, emotional intelligence, and creativity.",
    cta: "Read Comics",
    accent: "#ff6b6b",
    bg: "from-[#1a0a0a] via-[#2b1414] to-[#3d1e1e]",
    shape: "square",
    emoji: "💥",
    badges: ["Life Lessons", "Fun Stories", "Visual Learning"],
    link: "/mentoons-comics",
    items: [
      {
        name: "E-Comics",
        link: "/mentoons-comics?option=comic",
        color: "#ff6b6b",
      },
      {
        name: "Audio Comics",
        link: "/mentoons-comics?option=comic",
        color: "#ff8585",
      },
    ],
  },
  {
    id: 6,
    img: "/assets/home/newPage/bg/banner/Games banner.png",
    tag: "🎮 GAMES",
    headline: "Games",
    highlightWord: "Games",
    sub: "Interactive games designed to boost creativity, thinking skills, and problem-solving while having fun.",
    cta: "Play More Games",
    accent: "#8e7dff",
    bg: "from-[#0a061a] via-[#1b1433] to-[#2e1f55]",
    shape: "hexagon",
    emoji: "🕹️",
    badges: ["Brain Games", "Fun Learning", "Skill Building"],
    link: "/adda/game-lobby",
    items: [
      {
        name: "Cartoonmoji",
        link: "/adda/game-lobby/cartoonmoji",
        image: "/assets/adda/gameLobby/cartoonmoji.png",
      },
      {
        name: "Grid Flash",
        link: "/adda/game-lobby/grid-flash",
        image: "/assets/adda/gameLobby/gridFlash.png",
      },
      {
        name: "Mind Stack",
        link: "/adda/game-lobby/mind-stack",
        image: "/assets/adda/gameLobby/mindStack.png",
      },
      {
        name: "Flip and Match",
        link: "/adda/game-lobby/flip-and-match",
        image: "/assets/adda/gameLobby/flipAndMatch.png",
      },
      {
        name: "Stick Master",
        link: "/adda/game-lobby/stick-master",
        image: "/assets/adda/gameLobby/stickMaster.png",
      },
      {
        name: "ColorTube",
        link: "/adda/game-lobby/color-tube",
        image: "/assets/games/ColorTube/startBg2.jpg",
      },
    ],
  },
  {
    id: 7,
    img: "/assets/home/newPage/bg/banner/Quiz banner.png",
    tag: "❓ QUIZ",
    headline: "Quiz",
    highlightWord: "Quiz",
    sub: "Test your knowledge with exciting quizzes across topics like games, social media, technology, and more.",
    cta: "Start Quiz",
    accent: "#00d4ff",
    bg: "from-[#04141c] via-[#0b2b3a] to-[#124559]",
    shape: "diamond",
    emoji: "🧩",
    badges: ["Knowledge Test", "Multiple Topics", "Challenge Yourself"],
    link: "/quiz",
    items: [
      { name: "Logo Quiz", link: "/quiz", color: "#FFF3E0" },
      { name: "Music", link: "/quiz", color: "#FFE0B2" },
      { name: "Mobile Addiction", link: "/quiz", color: "#FFCC80" },
      { name: "Gaming Addiction", link: "/quiz", color: "#FFA726" },
      { name: "Gambling Addiction", link: "/quiz", color: "#FFA726" },
      { name: "Performance Addiction", link: "/quiz", color: "#FB8C00" },
      { name: "Entertainment Addiction", link: "/quiz", color: "#E65100" },
    ],
  },
];
