import { Slide } from "@/types";

export const SLIDES: Slide[] = [
  {
    id: 1,
    tag: "⚡ LIMITED OFFER",
    headline: "3 Day Trial",
    highlightWord: "Trial",
    sub: "Try everything free for 3 days — full access with zero hassle.",
    cta: "Claim Your Trial",
    accent: "#a8ff78",
    bg: "from-[#071a0e] via-[#0f2e1a] to-[#1a4a2e]",
    shape: "circle",
    emoji: "🎯",
    badges: ["✓ Full Access", "✓ Zero Risk"],
  },
  {
    id: 2,
    tag: "🎓 WORKSHOPS",
    headline: "Workshops",
    highlightWord: "Workshops",
    sub: "Workshops for ages 6–12 with hands-on play-based learning, and ages 13–19 with advanced, expert-led sessions.",
    cta: "Explore Workshops",
    accent: "#f9c74f",
    bg: "from-[#0a0a1e] via-[#1a1a2e] to-[#16213e]",
    shape: "triangle",
    emoji: "🧠",
    badges: ["Ages 6–12", "Ages 13–19", "Expert Led", "Live Sessions"],
  },
  {
    id: 3,
    tag: "🛍️ PRODUCTS",
    headline: "Products",
    highlightWord: "Products",
    sub: "Products built for kids, teens, adults and parents — designed around how each age group thinks, plays, and grows.",
    cta: "Shop by Age",
    accent: "#ff9f43",
    bg: "from-[#1a0505] via-[#2e0f0f] to-[#4a1a1a]",
    shape: "star",
    emoji: "🚀",
    badges: ["Kids", "Teens", "Adults", "Parents"],
  },

  {
    id: 4,
    tag: "🎧 PODCASTS",
    headline: "Podcasts",
    highlightWord: "Podcasts",
    sub: "Engaging audio stories, expert talks, and insightful discussions designed to inspire kids, teens, and parents.",
    cta: "Listen Now",
    accent: "#6dd5ed",
    bg: "from-[#04141c] via-[#0b2b3a] to-[#124559]",
    shape: "wave",
    emoji: "🎙️",
    badges: ["Storytelling", "Expert Talks", "Learning Audio"],
  },

  {
    id: 5,
    tag: "📚 COMICS",
    headline: "Comics",
    highlightWord: "Comics",
    sub: "Fun, meaningful comic stories that teach life lessons, emotional intelligence, and creativity.",
    cta: "Read Comics",
    accent: "#ff6b6b",
    bg: "from-[#1a0a0a] via-[#2b1414] to-[#3d1e1e]",
    shape: "square",
    emoji: "💥",
    badges: ["Life Lessons", "Fun Stories", "Visual Learning"],
  },
  {
    id: 6,
    tag: "🎮 GAMES",
    headline: "Games",
    highlightWord: "Games",
    sub: "Interactive games designed to boost creativity, thinking skills, and problem-solving while having fun.",
    cta: "Play Games",
    accent: "#8e7dff",
    bg: "from-[#0a061a] via-[#1b1433] to-[#2e1f55]",
    shape: "hexagon",
    emoji: "🕹️",
    badges: ["Brain Games", "Fun Learning", "Skill Building"],
  },
  {
    id: 7,
    tag: "❓ QUIZ",
    headline: "Quiz",
    highlightWord: "Quiz",
    sub: "Test your knowledge with exciting quizzes across topics like games, social media, technology, and more.",
    cta: "Start Quiz",
    accent: "#00d4ff",
    bg: "from-[#04141c] via-[#0b2b3a] to-[#124559]",
    shape: "diamond",
    emoji: "🧩",
    badges: ["Knowledge Test", "Multiple Topics", "Challenge Yourself"],
  },
];
