export const QUIZ_DATA = {
  social_and_comm: [
    {
      q: "Which company owns this logo?",
      options: { a: "Facebook", b: "Instagram", c: "Twitter", d: "Snapchat" },
      answer: "b",
      image: "instagram.png",
    },
    {
      q: "Identify the messaging app",
      options: { a: "Telegram", b: "Signal", c: "Messenger", d: "WhatsApp" },
      answer: "d",
      image: "whatsapp.png",
    },
    {
      q: "Identify the social media app",
      options: { a: "LinkedIn", b: "Facebook", c: "Twitter", d: "Reddit" },
      answer: "b",
      image: "facebook.png",
    },
    {
      q: "Identify the photo-sharing app",
      options: { a: "Pinterest", b: "Snapchat", c: "Instagram", d: "Flickr" },
      answer: "b",
      image: "snapchat.png",
    },
    {
      q: "Identify the short-video app",
      options: {
        a: "Instagram Reels",
        b: "YouTube Shorts",
        c: "TikTok",
        d: "Josh",
      },
      answer: "c",
      image: "tiktok.png",
    },
    {
      q: "Identify the professional networking site",
      options: { a: "Twitter", b: "LinkedIn", c: "Indeed", d: "Glassdoor" },
      answer: "b",
      image: "linkedin.png",
    },
    {
      q: "Which platform uses a bird as its former logo?",
      options: { a: "Twitter/X", b: "BlueSky", c: "Threads", d: "Mastodon" },
      answer: "a",
      image: "twitter.png",
    },
    {
      q: "Identify the community/chat app for gamers",
      options: { a: "Slack", b: "Discord", c: "Teams", d: "Skype" },
      answer: "b",
      image: "discord.png",
    },
    {
      q: "Identify the pinboard-style photo sharing site",
      options: { a: "Tumblr", b: "Pinterest", c: "Flickr", d: "Shutterstock" },
      answer: "b",
      image: "pinterest.png",
    },
    {
      q: "Which app uses a 'ghost' as its primary logo?",
      options: { a: "Snapchat", b: "Ghostery", c: "Casper", d: "Telegram" },
      answer: "a",
      image: "snapchat_logo.png",
    },
    {
      q: "Identify the video streaming platform",
      options: { a: "Vimeo", b: "Netflix", c: "YouTube", d: "Twitch" },
      answer: "c",
      image: "youtube.png",
    },
    {
      q: "Identify the work collaboration and chat tool",
      options: { a: "Slack", b: "Discord", c: "Skype", d: "WhatsApp" },
      answer: "a",
      image: "slack.png",
    },
    {
      q: "Which platform is known for its 'subreddit' communities?",
      options: { a: "Quora", b: "Reddit", c: "Tumblr", d: "Medium" },
      answer: "b",
      image: "reddit.png",
    },
    {
      q: "Identify the privacy-focused messaging app",
      options: { a: "WhatsApp", b: "Signal", c: "Viber", d: "Line" },
      answer: "b",
      image: "signal.png",
    },
    {
      q: "Identify the live-streaming platform popular with gamers",
      options: {
        a: "Mixer",
        b: "YouTube Live",
        c: "Twitch",
        d: "Facebook Gaming",
      },
      answer: "c",
      image: "twitch.png",
    },
    {
      q: "Which text-based app was launched by Meta to rival X (Twitter)?",
      options: { a: "Threads", b: "Mastodon", c: "BlueSky", d: "Post" },
      answer: "a",
      image: "threads.png",
    },
    {
      q: "Identify the business communication tool by Microsoft",
      options: { a: "Zoom", b: "Teams", c: "Webex", d: "Meet" },
      answer: "b",
      image: "microsoft_teams.png",
    },
    {
      q: "Identify the Q&A platform logo",
      options: {
        a: "Reddit",
        b: "Stack Overflow",
        c: "Quora",
        d: "Answers.com",
      },
      answer: "c",
      image: "quora.png",
    },
  ],
  tech_and_software: [
    {
      q: "Find the Brand Logo",
      options: { a: "Google", b: "Bing", c: "Yahoo", d: "DuckDuckGo" },
      answer: "a",
      image: "google.png",
    },
    {
      q: "Identify the browser logo",
      options: { a: "Chrome", b: "Edge", c: "Safari", d: "Firefox" },
      answer: "d",
      image: "firefox.png",
    },
    {
      q: "This logo belongs to which brand?",
      options: { a: "Apple", b: "Samsung", c: "Sony", d: "Microsoft" },
      answer: "a",
      image: "apple.png",
    },
    {
      q: "Which company owns this logo?",
      options: { a: "Meta", b: "Google", c: "Microsoft", d: "Amazon" },
      answer: "c",
      image: "microsoft.png",
    },
    {
      q: "Find the coding platform logo",
      options: { a: "GitLab", b: "Bitbucket", c: "GitHub", d: "SourceForge" },
      answer: "c",
      image: "github.png",
    },
    {
      q: "Guess the creative software suite",
      options: { a: "CorelDraw", b: "Affinity", c: "Adobe", d: "Autodesk" },
      answer: "c",
      image: "adobe.png",
    },
    {
      q: "Which company uses this 'M' shaped logo?",
      options: { a: "Motorola", b: "Mazda", c: "Monster", d: "Medium" },
      answer: "a",
      image: "motorola.png",
    },
    {
      q: "Identify the cloud computing service logo",
      options: { a: "AWS", b: "Azure", c: "Google Cloud", d: "Oracle" },
      answer: "a",
      image: "aws.png",
    },
    {
      q: "Identify the AI assistant logo",
      options: { a: "ChatGPT", b: "Claude", c: "Gemini", d: "Perplexity" },
      answer: "c",
      image: "gemini.png",
    },
    {
      q: "This logo belongs to which popular AI research lab?",
      options: { a: "DeepMind", b: "OpenAI", c: "Anthropic", d: "Meta AI" },
      answer: "b",
      image: "openai.png",
    },
    {
      q: "Identify the leading graphics card manufacturer logo",
      options: { a: "Intel", b: "AMD", c: "Nvidia", d: "ASUS" },
      answer: "c",
      image: "nvidia.png",
    },
    {
      q: "Which coding editor uses this blue 'ribbon' icon?",
      options: { a: "Sublime Text", b: "Atom", c: "VS Code", d: "Notepad++" },
      answer: "c",
      image: "vscode.png",
    },
    {
      q: "Identify the logo for this containerization platform",
      options: { a: "Kubernetes", b: "Docker", c: "Terraform", d: "Jenkins" },
      answer: "b",
      image: "docker.png",
    },
    {
      q: "This 'play button' logo belongs to which music streaming giant?",
      options: {
        a: "Apple Music",
        b: "Spotify",
        c: "YouTube Music",
        d: "Tidal",
      },
      answer: "c",
      image: "youtube_music.png",
    },
    {
      q: "Identify the logo of the world's largest online encyclopedia",
      options: { a: "Britannica", b: "Wikipedia", c: "Quora", d: "Wiktionary" },
      answer: "b",
      image: "wikipedia.png",
    },
    {
      q: "Which company uses a blue 'Salesforce' cloud logo?",
      options: { a: "Oracle", b: "SAP", c: "Salesforce", d: "Workday" },
      answer: "c",
      image: "salesforce.png",
    },
    {
      q: "Identify the logo for this collaborative design tool",
      options: { a: "Canva", b: "Sketch", c: "Figma", d: "InVision" },
      answer: "c",
      image: "figma.png",
    },
    {
      q: "Identify the video conferencing tool logo",
      options: { a: "Skype", b: "Zoom", c: "Google Meet", d: "Webex" },
      answer: "b",
      image: "zoom.png",
    },
  ],
  gaming_and_entertainment: [
    {
      q: "Which gaming console brand is this?",
      options: { a: "Xbox", b: "PlayStation", c: "Nintendo", d: "Sega" },
      answer: "b",
      image: "playstation.png",
    },
    {
      q: "Identify the game engine logo",
      options: { a: "Unreal Engine", b: "Unity", c: "Godot", d: "CryEngine" },
      answer: "b",
      image: "unity.png",
    },
    {
      q: "Which platform features a green 'N'?",
      options: { a: "Nvidia", b: "Netflix", c: "Nintendo", d: "Nokia" },
      answer: "b",
      image: "netflix.png",
    },
    {
      q: "Guess the video platform logo",
      options: { a: "Vimeo", b: "Netflix", c: "YouTube", d: "Dailymotion" },
      answer: "c",
      image: "youtube.png",
    },
    {
      q: "Identify the music streaming service",
      options: {
        a: "Apple Music",
        b: "Spotify",
        c: "Amazon Music",
        d: "Gaana",
      },
      answer: "b",
      image: "spotify.png",
    },
    {
      q: "Which brand uses the 'Switch' logo?",
      options: { a: "Sony", b: "Microsoft", c: "Nintendo", d: "Steam" },
      answer: "c",
      image: "nintendo.png",
    },
    {
      q: "Identify the PC gaming storefront",
      options: { a: "Epic Games", b: "Steam", c: "Origin", d: "GOG" },
      answer: "b",
      image: "steam.png",
    },
    [
      {
        q: "Identify the live-streaming platform with the purple logo",
        options: { a: "Mixer", b: "Twitch", c: "Dailymotion", d: "Vimeo" },
        answer: "b",
        image: "twitch.png",
      },
      {
        q: "Which gaming brand uses a green 'X' logo?",
        options: { a: "Xerox", b: "Xfinity", c: "Xbox", d: "X" },
        answer: "c",
        image: "xbox.png",
      },
      {
        q: "Identify the logo of the 'Fortnite' creator",
        options: { a: "Ubisoft", b: "EA", c: "Epic Games", d: "Activision" },
        answer: "c",
        image: "epic_games.png",
      },
      {
        q: "This 'H' logo belongs to which streaming network?",
        options: { a: "Hulu", b: "HBO", c: "History Channel", d: "Hotstar" },
        answer: "a",
        image: "hulu.png",
      },
      {
        q: "Identify the iconic gaming mascot/brand logo",
        options: { a: "Sega", b: "Atari", c: "Bandai Namco", d: "Capcom" },
        answer: "b",
        image: "atari.png",
      },
      {
        q: "Which company uses a blue 'S' logo (Sonic's creator)?",
        options: { a: "Sony", b: "Sega", c: "Square Enix", d: "Supercell" },
        answer: "b",
        image: "sega.png",
      },
      {
        q: "Identify the anime streaming service logo",
        options: { a: "Funimation", b: "Crunchyroll", c: "Netflix", d: "Hulu" },
        answer: "b",
        image: "crunchyroll.png",
      },
      {
        q: "Which studio uses a 'swirl' logo and makes Assassin's Creed?",
        options: { a: "Rockstar", b: "Ubisoft", c: "Bethesda", d: "Valve" },
        answer: "b",
        image: "ubisoft.png",
      },
      {
        q: "Identify the logo of the 'Grand Theft Auto' developer",
        options: {
          a: "Rockstar Games",
          b: "EA Sports",
          c: "2K Games",
          d: "Infinity Ward",
        },
        answer: "a",
        image: "rockstar.png",
      },
      {
        q: "Which platform uses the 'Mountain' logo for movies?",
        options: { a: "Universal", b: "Paramount+", c: "Disney+", d: "MGM" },
        answer: "b",
        image: "paramount_plus.png",
      },
    ],
  ],
  food_and_lifestyle: [
    {
      q: "Which coffee chain owns this logo?",
      options: {
        a: "Costa Coffee",
        b: "Dunkin'",
        c: "Starbucks",
        d: "Tim Hortons",
      },
      answer: "c",
      image: "starbucks.png",
    },
    {
      q: "This logo belongs to which fast food chain?",
      options: { a: "Burger King", b: "KFC", c: "Subway", d: "McDonald's" },
      answer: "d",
      image: "mcdonalds.png",
    },
    {
      q: "Identify the beverage brand",
      options: { a: "Pepsi", b: "Coca-Cola", c: "Red Bull", d: "Sprite" },
      answer: "b",
      image: "cocacola.png",
    },
    {
      q: "Which energy drink uses two bulls?",
      options: { a: "Monster", b: "Red Bull", c: "Rockstar", d: "Sting" },
      answer: "b",
      image: "redbull.png",
    },
    {
      q: "Identify the furniture retailer",
      options: { a: "Pepperfry", b: "IKEA", c: "Wayfair", d: "Urban Ladder" },
      answer: "b",
      image: "ikea.png",
    },
    {
      q: "Identify the luxury fashion brand",
      options: { a: "Gucci", b: "Louis Vuitton", c: "Prada", d: "Chanel" },
      answer: "b",
      image: "louis_vuitton.png",
    },
    {
      q: "Identify the sportswear brand with the 'swoosh' logo",
      options: { a: "Adidas", b: "Puma", c: "Nike", d: "Reebok" },
      answer: "c",
      image: "nike.png",
    },
    {
      q: "Which chocolate brand uses a mountain (the Matterhorn) in its logo?",
      options: { a: "Hershey's", b: "Toblerone", c: "Dairy Milk", d: "Lindt" },
      answer: "b",
      image: "toblerone.png",
    },
    {
      q: "Identify the fast-food chain known for its 'Golden Arches'",
      options: {
        a: "Burger King",
        b: "McDonald's",
        c: "Wendy's",
        d: "Hardee's",
      },
      answer: "b",
      image: "mcdonalds_arches.png",
    },
    {
      q: "Which brand uses an alligator as its logo?",
      options: { a: "Crocs", b: "Lacoste", c: "Polo", d: "Everlast" },
      answer: "b",
      image: "lacoste.png",
    },
    {
      q: "Identify the donut and coffee house chain",
      options: {
        a: "Krispy Kreme",
        b: "Dunkin'",
        c: "Tim Hortons",
        d: "Mad Over Donuts",
      },
      answer: "b",
      image: "dunkin.png",
    },
    {
      q: "This logo belongs to which luxury jewelry retailer?",
      options: {
        a: "Cartier",
        b: "Tiffany & Co.",
        c: "Pandora",
        d: "Swarovski",
      },
      answer: "b",
      image: "tiffany.png",
    },
    {
      q: "Identify the iconic sandwich shop logo",
      options: { a: "Subway", b: "Quiznos", c: "Jimmy John's", d: "Potbelly" },
      answer: "a",
      image: "subway.png",
    },
    {
      q: "Which Italian brand uses a 'Medusa head' in its logo?",
      options: { a: "Gucci", b: "Versace", c: "Prada", d: "Armani" },
      answer: "b",
      image: "versace.png",
    },
    {
      q: "Identify the famous potato chip brand",
      options: { a: "Doritos", b: "Pringles", c: "Lay's", d: "Cheetos" },
      answer: "c",
      image: "lays.png",
    },
    {
      q: "Which sportswear brand features three parallel stripes?",
      options: { a: "Nike", b: "New Balance", c: "Adidas", d: "Under Armour" },
      answer: "c",
      image: "adidas.png",
    },
  ],
  automobiles_and_hardware: [
    {
      q: "This logo represents which brand?",
      options: { a: "Tesla", b: "BMW", c: "Audi", d: "Mercedes" },
      answer: "a",
      image: "tesla.png",
    },
    {
      q: "Which luxury car brand uses this logo?",
      options: { a: "Ferrari", b: "Lamborghini", c: "Porsche", d: "Maserati" },
      answer: "c",
      image: "porsche.png",
    },
    {
      q: "Identify the chip manufacturer",
      options: { a: "Intel", b: "AMD", c: "Nvidia", d: "Qualcomm" },
      answer: "a",
      image: "intel.png",
    },
    {
      q: "Identify the camera brand",
      options: { a: "Nikon", b: "Canon", c: "Fujifilm", d: "Sony" },
      answer: "b",
      image: "canon.png",
    },
    {
      q: "Identify the PC brand",
      options: { a: "HP", b: "Dell", c: "Lenovo", d: "Asus" },
      answer: "b",
      image: "dell.png",
    },
    {
      q: "This logo with four rings belongs to?",
      options: { a: "BMW", b: "Audi", c: "Toyota", d: "Honda" },
      answer: "b",
      image: "audi.png",
    },
    [
      {
        q: "Which car brand features a 'Fighting Bull' in its logo?",
        options: { a: "Ferrari", b: "Lamborghini", c: "Porsche", d: "Peugeot" },
        answer: "b",
        image: "lamborghini.png",
      },
      {
        q: "Identify the Japanese car brand with a logo of three overlapping ovals",
        options: { a: "Honda", b: "Mazda", c: "Toyota", d: "Nissan" },
        answer: "c",
        image: "toyota.png",
      },
      {
        q: "This three-pointed star logo belongs to which manufacturer?",
        options: {
          a: "Mercedes-Benz",
          b: "Mitsubishi",
          c: "Subaru",
          d: "Chrysler",
        },
        answer: "a",
        image: "mercedes.png",
      },
      {
        q: "Identify the leading manufacturer of smartphone processors (Snapdragon)",
        options: { a: "Intel", b: "Qualcomm", c: "Apple", d: "MediaTek" },
        answer: "b",
        image: "qualcomm.png",
      },
      {
        q: "Which luxury brand uses a 'Trident' as its logo?",
        options: { a: "Maserati", b: "Bugatti", c: "Alfa Romeo", d: "Bentley" },
        answer: "a",
        image: "maserati.png",
      },
      {
        q: "Identify the logo of this South Korean tech giant",
        options: { a: "LG", b: "Samsung", c: "Hyundai", d: "Sony" },
        answer: "b",
        image: "samsung.png",
      },
      {
        q: "This logo featuring six stars (the Pleiades) belongs to?",
        options: { a: "Subaru", b: "Volvo", c: "Ford", d: "Polestar" },
        answer: "a",
        image: "subaru.png",
      },
      {
        q: "Identify the brand known for the 'ThinkPad' and 'Yoga' series",
        options: { a: "Acer", b: "HP", c: "Lenovo", d: "Microsoft Surface" },
        answer: "c",
        image: "lenovo.png",
      },
      {
        q: "Which camera manufacturer uses a red 'L' or a distinctive red dot?",
        options: { a: "Leica", b: "Lumix", c: "Fujifilm", d: "Kodak" },
        answer: "a",
        image: "leica.png",
      },
      {
        q: "Identify the logo for this high-performance graphics card brand",
        options: {
          a: "Intel Arc",
          b: "AMD Radeon",
          c: "Nvidia GeForce",
          d: "MSI",
        },
        answer: "c",
        image: "nvidia_geforce.png",
      },
    ],
  ],
  finance_and_travel: [
    {
      q: "Identify the payment processor",
      options: { a: "Stripe", b: "PayPal", c: "Visa", d: "Mastercard" },
      answer: "b",
      image: "paypal.png",
    },
    {
      q: "Find the credit card network logo",
      options: { a: "Visa", b: "Mastercard", c: "Amex", d: "Discover" },
      answer: "b",
      image: "mastercard.png",
    },
    {
      q: "Identify the crypto platform",
      options: { a: "Binance", b: "Coinbase", c: "Kraken", d: "WazirX" },
      answer: "a",
      image: "binance.png",
    },
    {
      q: "This logo belongs to which airline?",
      options: {
        a: "Emirates",
        b: "Qatar Airways",
        c: "Delta",
        d: "Singapore Airlines",
      },
      answer: "a",
      image: "emirates.png",
    },
    {
      q: "Identify the travel booking app",
      options: { a: "Goibibo", b: "MakeMyTrip", c: "Yatra", d: "Airbnb" },
      answer: "b",
      image: "makemytrip.png",
    },
    {
      q: "Which app uses a 'homestyle' logo for rentals?",
      options: { a: "Expedia", b: "Trivago", c: "Airbnb", d: "Booking.com" },
      answer: "c",
      image: "airbnb.png",
    },
    {
      q: "Identify the cryptocurrency with the 'diamond' or 'gem' shaped logo",
      options: { a: "Bitcoin", b: "Ethereum", c: "Litecoin", d: "Cardano" },
      answer: "b",
      image: "ethereum.png",
    },
    {
      q: "Which airline uses a 'Kangaroo' as its iconic logo?",
      options: {
        a: "Air New Zealand",
        b: "Singapore Airlines",
        c: "Qantas",
        d: "Lufthansa",
      },
      answer: "c",
      image: "qantas.png",
    },
    {
      q: "Identify the logo of this premium credit card and travel services provider",
      options: {
        a: "Visa",
        b: "American Express",
        c: "Mastercard",
        d: "Diners Club",
      },
      answer: "b",
      image: "amex.png",
    },
    {
      q: "Which investment giant uses a 'Bull' in its branding?",
      options: {
        a: "Merrill Lynch",
        b: "Goldman Sachs",
        c: "Morgan Stanley",
        d: "JP Morgan",
      },
      answer: "a",
      image: "merrill_lynch.png",
    },
    {
      q: "Identify the European airline with the 'Crowned Crane' logo",
      options: { a: "KLM", b: "Air France", c: "Lufthansa", d: "Swiss Air" },
      answer: "c",
      image: "lufthansa.png",
    },
    {
      q: "Which digital bank or fintech app uses a minimalist 'M' logo?",
      options: { a: "Monzo", b: "Revolut", c: "N26", d: "Starling" },
      answer: "a",
      image: "monzo.png",
    },
    {
      q: "Identify the logo of the world's largest hotel search engine",
      options: { a: "Trivago", b: "Expedia", c: "KAYAK", d: "TripAdvisor" },
      answer: "a",
      image: "trivago.png",
    },
    {
      q: "Which airline is famous for its 'Red Maple Leaf' tail logo?",
      options: {
        a: "Swiss",
        b: "Air Canada",
        c: "Japan Airlines",
        d: "Austrian Airlines",
      },
      answer: "b",
      image: "air_canada.png",
    },
    {
      q: "Identify the global investment management firm with a 'Rock' logo",
      options: {
        a: "BlackRock",
        b: "Vanguard",
        c: "Fidelity",
        d: "Charles Schwab",
      },
      answer: "a",
      image: "blackrock.png",
    },
    {
      q: "This blue 'owl' logo belongs to which travel review site?",
      options: { a: "Yelp", b: "TripAdvisor", c: "Booking.com", d: "Agoda" },
      answer: "b",
      image: "tripadvisor.png",
    },
  ],
};
