import { QuizGame } from "@/types/adda/quiz";

export const QUIZ_DATA_GAME: QuizGame[] = [
  {
    _id: "FC124",
    title: "Logo",
    category: [
      {
        quizId: "QD_01",
        category: "socialMedia and Communication",
        questions: [
          {
            q: "Which company owns this logo?",
            options: {
              a: "Facebook",
              b: "Instagram",
              c: "Twitter",
              d: "Snapchat",
            },
            answer: "b",
            image: "/assets/Quiz/logo/instagram.png",
          },
          {
            q: "Identify the messaging app",
            options: {
              a: "Telegram",
              b: "Signal",
              c: "Messenger",
              d: "WhatsApp",
            },
            answer: "d",
            image: "/assets/Quiz/logo/whatsapp.png",
          },
          {
            q: "Identify the social media app",
            options: {
              a: "LinkedIn",
              b: "Facebook",
              c: "Twitter",
              d: "Reddit",
            },
            answer: "b",
            image: "/assets/Quiz/logo/facebook.png",
          },
          {
            q: "Identify the photo-sharing app",
            options: {
              a: "Pinterest",
              b: "Snapchat",
              c: "Instagram",
              d: "Flickr",
            },
            answer: "b",
            image: "/assets/Quiz/logo/snapchat.png",
          },
          {
            q: "Identify the short-video app",
            options: {
              a: "Instagram Reels",
              b: "YouTube Shorts",
              c: "TikTok",
              d: "Josh",
            },
            answer: "c",
            image: "/assets/Quiz/logo/tik-tok.png",
          },
          {
            q: "Identify the professional networking site",
            options: {
              a: "Twitter",
              b: "LinkedIn",
              c: "Indeed",
              d: "Glassdoor",
            },
            answer: "b",
            image: "/assets/Quiz/logo/linkedin.png",
          },
          {
            q: "Which platform uses a bird as its former logo?",
            options: {
              a: "Twitter/X",
              b: "BlueSky",
              c: "Threads",
              d: "Mastodon",
            },
            answer: "a",
            image: "/assets/Quiz/logo/x.png",
          },
          {
            q: "Identify the community/chat app for gamers",
            options: { a: "Slack", b: "Discord", c: "Teams", d: "Skype" },
            answer: "b",
            image: "/assets/Quiz/logo/discord.png",
          },
          {
            q: "Identify the pinboard-style photo sharing site",
            options: {
              a: "Tumblr",
              b: "Pinterest",
              c: "Flickr",
              d: "Shutterstock",
            },
            answer: "b",
            image: "/assets/Quiz/logo/pinterest.png",
          },
          {
            q: "Which app uses a 'ghost' as its primary logo?",
            options: {
              a: "Snapchat",
              b: "Ghostery",
              c: "Casper",
              d: "Telegram",
            },
            answer: "a",
            image: "/assets/Quiz/logo/snapchat.png",
          },
          {
            q: "Identify the video streaming platform",
            options: { a: "Vimeo", b: "Netflix", c: "YouTube", d: "Twitch" },
            answer: "c",
            image: "/assets/Quiz/logo/youtube.png",
          },
          {
            q: "Identify the work collaboration and chat tool",
            options: { a: "Slack", b: "Discord", c: "Skype", d: "WhatsApp" },
            answer: "a",
            image: "/assets/Quiz/logo/slack.png",
          },
          {
            q: "Which platform is known for its 'subreddit' communities?",
            options: { a: "Quora", b: "Reddit", c: "Tumblr", d: "Medium" },
            answer: "b",
            image: "/assets/Quiz/logo/reddit.png",
          },
          {
            q: "Identify the privacy-focused messaging app",
            options: { a: "WhatsApp", b: "Signal", c: "Viber", d: "Line" },
            answer: "b",
            image: "/assets/Quiz/logo/signal.png",
          },
          {
            q: "Identify the live-streaming platform popular with gamers",
            options: {
              a: "Mixer",
              b: "YouTube Live",
              c: "Twitch",
              d: "Facebook Gaming",
            },
            answer: "c",
            image: "/assets/Quiz/logo/twitch.png",
          },
          {
            q: "Which text-based app was launched by Meta to rival X (Twitter)?",
            options: { a: "Threads", b: "Mastodon", c: "BlueSky", d: "Post" },
            answer: "a",
            image: "/assets/Quiz/logo/threads.png",
          },
          {
            q: "Identify the business communication tool by Microsoft",
            options: { a: "Zoom", b: "Teams", c: "Webex", d: "Meet" },
            answer: "b",
            image: "/assets/Quiz/logo/microsoft-teams.png",
          },
          {
            q: "Identify the Q&A platform logo",
            options: {
              a: "Reddit",
              b: "Stack Overflow",
              c: "Quora",
              d: "Answers.com",
            },
            answer: "c",
            image: "/assets/Quiz/logo/quora.png",
          },
        ],
      },
      {
        quizId: "QD_02",
        category: "Tech and Software",
        questions: [
          {
            q: "Find the Brand Logo",
            options: { a: "Google", b: "Bing", c: "Yahoo", d: "DuckDuckGo" },
            answer: "a",
            image: "/assets/Quiz/logo/google.png",
          },
          {
            q: "Identify the browser logo",
            options: { a: "Chrome", b: "Edge", c: "Safari", d: "Firefox" },
            answer: "d",
            image: "/assets/Quiz/logo/firefox.png",
          },
          {
            q: "This logo belongs to which brand?",
            options: { a: "Apple", b: "Samsung", c: "Sony", d: "Microsoft" },
            answer: "a",
            image: "/assets/Quiz/logo/apple.png",
          },
          {
            q: "Which company owns this logo?",
            options: { a: "Meta", b: "Google", c: "Microsoft", d: "Amazon" },
            answer: "c",
            image: "/assets/Quiz/logo/microsoft.png",
          },
          {
            q: "Find the coding platform logo",
            options: {
              a: "GitLab",
              b: "Bitbucket",
              c: "GitHub",
              d: "SourceForge",
            },
            answer: "c",
            image: "/assets/Quiz/logo/github.png",
          },
          {
            q: "Guess the creative software suite",
            options: {
              a: "CorelDraw",
              b: "Affinity",
              c: "Adobe",
              d: "Autodesk",
            },
            answer: "c",
            image: "/assets/Quiz/logo/adobe.png",
          },
          {
            q: "Which company uses this 'M' shaped logo?",
            options: { a: "Motorola", b: "Mazda", c: "Monster", d: "Medium" },
            answer: "a",
            image: "/assets/Quiz/logo/motorola.png",
          },
          {
            q: "Identify the cloud computing service logo",
            options: { a: "AWS", b: "Azure", c: "Google Cloud", d: "Oracle" },
            answer: "a",
            image: "/assets/Quiz/logo/aws.png",
          },
          {
            q: "Identify the AI assistant logo",
            options: {
              a: "ChatGPT",
              b: "Claude",
              c: "Gemini",
              d: "Perplexity",
            },
            answer: "c",
            image: "/assets/Quiz/logo/google-gemini.png",
          },
          {
            q: "This logo belongs to which popular AI research lab?",
            options: {
              a: "DeepMind",
              b: "OpenAI",
              c: "Anthropic",
              d: "Meta AI",
            },
            answer: "b",
            image: "/assets/Quiz/logo/openai.png",
          },
          {
            q: "Identify the leading graphics card manufacturer logo",
            options: { a: "Intel", b: "AMD", c: "Nvidia", d: "ASUS" },
            answer: "c",
            image: "/assets/Quiz/logo/nvidia.png",
          },
          {
            q: "Which coding editor uses this blue 'ribbon' icon?",
            options: {
              a: "Sublime Text",
              b: "Atom",
              c: "VS Code",
              d: "Notepad++",
            },
            answer: "c",
            image: "/assets/Quiz/logo/vscode.png",
          },
          {
            q: "Identify the logo for this containerization platform",
            options: {
              a: "Kubernetes",
              b: "Docker",
              c: "Terraform",
              d: "Jenkins",
            },
            answer: "b",
            image: "/assets/Quiz/logo/docker.png",
          },
          {
            q: "This 'play button' logo belongs to which music streaming giant?",
            options: {
              a: "Apple Music",
              b: "Spotify",
              c: "YouTube Music",
              d: "Tidal",
            },
            answer: "c",
            image: "/assets/Quiz/logo/youtube-music.png",
          },
          {
            q: "Identify the logo of the world's largest online encyclopedia",
            options: {
              a: "Britannica",
              b: "Wikipedia",
              c: "Quora",
              d: "Wiktionary",
            },
            answer: "b",
            image: "/assets/Quiz/logo/wikipedia.png",
          },
          {
            q: "Which company uses a blue 'Salesforce' cloud logo?",
            options: { a: "Oracle", b: "SAP", c: "Salesforce", d: "Workday" },
            answer: "c",
            image: "/assets/Quiz/logo/salesforce.png",
          },
          {
            q: "Identify the logo for this collaborative design tool",
            options: { a: "Canva", b: "Sketch", c: "Figma", d: "InVision" },
            answer: "c",
            image: "/assets/Quiz/logo/figma.png",
          },
          {
            q: "Identify the video conferencing tool logo",
            options: { a: "Skype", b: "Zoom", c: "Google Meet", d: "Webex" },
            answer: "b",
            image: "/assets/Quiz/logo/zoom.png",
          },
        ],
      },
      {
        quizId: "QD_03",
        category: "Gaming and Entertainment",
        questions: [
          {
            q: "Which gaming console brand is this?",
            options: { a: "Xbox", b: "PlayStation", c: "Nintendo", d: "Sega" },
            answer: "b",
            image: "/assets/Quiz/logo/playstation.png",
          },
          {
            q: "Identify the game engine logo",
            options: {
              a: "Unreal Engine",
              b: "Unity",
              c: "Godot",
              d: "CryEngine",
            },
            answer: "b",
            image: "/assets/Quiz/logo/unity-game-engine.png",
          },
          {
            q: "Which platform features a red 'N'?",
            options: { a: "Nvidia", b: "Netflix", c: "Nintendo", d: "Nokia" },
            answer: "b",
            image: "/assets/Quiz/logo/netflix.png",
          },
          {
            q: "Guess the video platform logo",
            options: {
              a: "Vimeo",
              b: "Netflix",
              c: "YouTube",
              d: "Dailymotion",
            },
            answer: "c",
            image: "/assets/Quiz/logo/youtube.png",
          },
          {
            q: "Identify the music streaming service",
            options: {
              a: "Apple Music",
              b: "Spotify",
              c: "Amazon Music",
              d: "Gaana",
            },
            answer: "b",
            image: "/assets/Quiz/logo/spotify.png",
          },
          {
            q: "Which brand uses the 'Switch' logo?",
            options: { a: "Sony", b: "Microsoft", c: "Nintendo", d: "Steam" },
            answer: "c",
            image: "/assets/Quiz/logo/Nintendo.png",
          },
          {
            q: "Identify the PC gaming storefront",
            options: { a: "Epic Games", b: "Steam", c: "Origin", d: "GOG" },
            answer: "b",
            image: "/assets/Quiz/logo/steam.png",
          },
          {
            q: "Identify the live-streaming platform with the purple logo",
            options: {
              a: "Mixer",
              b: "Twitch",
              c: "Dailymotion",
              d: "Vimeo",
            },
            answer: "b",
            image: "/assets/Quiz/logo/twitch.png",
          },
          {
            q: "Which gaming brand uses a green 'X' logo?",
            options: { a: "Xerox", b: "Xfinity", c: "Xbox", d: "X" },
            answer: "c",
            image: "/assets/Quiz/logo/xbox.png",
          },
          {
            q: "Identify the logo of the 'Fortnite' creator",
            options: {
              a: "Ubisoft",
              b: "EA",
              c: "Epic Games",
              d: "Activision",
            },
            answer: "c",
            image: "/assets/Quiz/logo/Epic-games.png",
          },
          {
            q: "This 'H' logo belongs to which streaming network?",
            options: {
              a: "Hulu",
              b: "HBO",
              c: "History Channel",
              d: "Hotstar",
            },
            answer: "a",
            image: "/assets/Quiz/logo/hulu.png",
          },
          {
            q: "Identify the iconic gaming mascot/brand logo",
            options: {
              a: "Sega",
              b: "Atari",
              c: "Bandai Namco",
              d: "Capcom",
            },
            answer: "b",
            image: "/assets/Quiz/logo/atari.png",
          },
          {
            q: "Which company uses a blue 'S' logo (Sonic's creator)?",
            options: {
              a: "Sony",
              b: "Sega",
              c: "Square Enix",
              d: "Supercell",
            },
            answer: "b",
            image: "/assets/Quiz/logo/sega.png",
          },
          {
            q: "Identify the anime streaming service logo",
            options: {
              a: "Funimation",
              b: "Crunchyroll",
              c: "Netflix",
              d: "Hulu",
            },
            answer: "b",
            image: "/assets/Quiz/logo/crunchyRoll.png",
          },
          {
            q: "Which studio uses a 'swirl' logo and makes Assassin's Creed?",
            options: {
              a: "Rockstar",
              b: "Ubisoft",
              c: "Bethesda",
              d: "Valve",
            },
            answer: "b",
            image: "/assets/Quiz/logo/ubisoft.png",
          },
          {
            q: "Identify the logo of the 'Grand Theft Auto' developer",
            options: {
              a: "Rockstar Games",
              b: "EA Sports",
              c: "2K Games",
              d: "Infinity Ward",
            },
            answer: "a",
            image: "/assets/Quiz/logo/rockstar.png",
          },
          {
            q: "Which platform uses the 'Mountain' logo for movies?",
            options: {
              a: "Universal",
              b: "Paramount+",
              c: "Disney+",
              d: "MGM",
            },
            answer: "b",
            image: "/assets/Quiz/logo/paramount.png",
          },
        ],
      },
      {
        quizId: "QD_04",
        category: "Food and Lifestyle",
        questions: [
          {
            q: "Which coffee chain owns this logo?",
            options: {
              a: "Costa Coffee",
              b: "Dunkin'",
              c: "Starbucks",
              d: "Tim Hortons",
            },
            answer: "c",
            image: "/assets/Quiz/logo/starbucks.png",
          },
          {
            q: "This logo belongs to which fast food chain?",
            options: {
              a: "Burger King",
              b: "KFC",
              c: "Subway",
              d: "McDonald's",
            },
            answer: "d",
            image: "/assets/Quiz/logo/mcDonald.png",
          },
          {
            q: "Identify the beverage brand",
            options: { a: "Pepsi", b: "Coca-Cola", c: "Red Bull", d: "Sprite" },
            answer: "b",
            image: "/assets/Quiz/logo/cocaCola.png",
          },
          {
            q: "Which energy drink uses two bulls?",
            options: { a: "Monster", b: "Red Bull", c: "Rockstar", d: "Sting" },
            answer: "b",
            image: "/assets/Quiz/logo/redbull.png",
          },
          {
            q: "Identify the furniture retailer",
            options: {
              a: "Pepperfry",
              b: "IKEA",
              c: "Wayfair",
              d: "Urban Ladder",
            },
            answer: "b",
            image: "/assets/Quiz/logo/ikea.png",
          },
          {
            q: "Identify the luxury fashion brand",
            options: {
              a: "Gucci",
              b: "Louis Vuitton",
              c: "Prada",
              d: "Chanel",
            },
            answer: "b",
            image: "/assets/Quiz/logo/louis_vuitton.png",
          },
          {
            q: "Identify the sportswear brand with the 'swoosh' logo",
            options: { a: "Adidas", b: "Puma", c: "Nike", d: "Reebok" },
            answer: "c",
            image: "/assets/Quiz/logo/nike.png",
          },
          {
            q: "Which chocolate brand uses a mountain (the Matterhorn) in its logo?",
            options: {
              a: "Hershey's",
              b: "Toblerone",
              c: "Dairy Milk",
              d: "Lindt",
            },
            answer: "b",
            image: "/assets/Quiz/logo/toblerone.png",
          },
          {
            q: "Identify the fast-food chain known for its 'Golden Arches'",
            options: {
              a: "Burger King",
              b: "McDonald's",
              c: "Wendy's",
              d: "Hardee's",
            },
            answer: "b",
            image: "/assets/Quiz/logo/mcDonald.png",
          },
          {
            q: "Which brand uses an alligator as its logo?",
            options: { a: "Crocs", b: "Lacoste", c: "Polo", d: "Everlast" },
            answer: "b",
            image: "/assets/Quiz/logo/lacoste.png",
          },
          {
            q: "Identify the donut and coffee house chain",
            options: {
              a: "Krispy Kreme",
              b: "Dunkin'",
              c: "Tim Hortons",
              d: "Mad Over Donuts",
            },
            answer: "b",
            image: "/assets/Quiz/logo/dunkin.jpg",
          },
          {
            q: "This logo belongs to which luxury jewelry retailer?",
            options: {
              a: "Cartier",
              b: "Tiffany & Co.",
              c: "Pandora",
              d: "Swarovski",
            },
            answer: "b",
            image: "/assets/Quiz/logo/tiffany and co.jpg",
          },
          {
            q: "Identify the iconic sandwich shop logo",
            options: {
              a: "Subway",
              b: "Quiznos",
              c: "Jimmy John's",
              d: "Potbelly",
            },
            answer: "a",
            image: "/assets/Quiz/logo/subway.png",
          },
          {
            q: "Which Italian brand uses a 'Medusa head' in its logo?",
            options: { a: "Gucci", b: "Versace", c: "Prada", d: "Armani" },
            answer: "b",
            image: "/assets/Quiz/logo/versace.png",
          },
          {
            q: "Identify the famous potato chip brand",
            options: { a: "Doritos", b: "Pringles", c: "Lay's", d: "Cheetos" },
            answer: "c",
            image: "/assets/Quiz/logo/lays.png",
          },
          {
            q: "Which sportswear brand features three parallel stripes?",
            options: {
              a: "Nike",
              b: "New Balance",
              c: "Adidas",
              d: "Under Armour",
            },
            answer: "c",
            image: "/assets/Quiz/logo/adidas.png",
          },
        ],
      },
      {
        quizId: "QD_05",
        category: "Automobiles and Hardware",
        questions: [
          {
            q: "This logo represents which brand?",
            options: { a: "Tesla", b: "BMW", c: "Audi", d: "Mercedes" },
            answer: "a",
            image: "/assets/Quiz/logo/tesla.png",
          },
          {
            q: "Which luxury car brand uses this logo?",
            options: {
              a: "Ferrari",
              b: "Lamborghini",
              c: "Porsche",
              d: "Maserati",
            },
            answer: "c",
            image: "/assets/Quiz/logo/porsche.png",
          },
          {
            q: "Identify the chip manufacturer",
            options: { a: "Intel", b: "AMD", c: "Nvidia", d: "Qualcomm" },
            answer: "a",
            image: "/assets/Quiz/logo/intel.png",
          },
          {
            q: "Identify the camera brand",
            options: { a: "Nikon", b: "Canon", c: "Fujifilm", d: "Sony" },
            answer: "b",
            image: "/assets/Quiz/logo/canon.png",
          },
          {
            q: "Identify the PC brand",
            options: { a: "HP", b: "Dell", c: "Lenovo", d: "Asus" },
            answer: "b",
            image: "/assets/Quiz/logo/dell.png",
          },
          {
            q: "This logo with four rings belongs to?",
            options: { a: "BMW", b: "Audi", c: "Toyota", d: "Honda" },
            answer: "b",
            image: "/assets/Quiz/logo/audi.png",
          },
          {
            q: "Which car brand features a 'Fighting Bull' in its logo?",
            options: {
              a: "Ferrari",
              b: "Lamborghini",
              c: "Porsche",
              d: "Peugeot",
            },
            answer: "b",
            image: "/assets/Quiz/logo/lamborgini.png",
          },
          {
            q: "Identify the Japanese car brand with a logo of three overlapping ovals",
            options: { a: "Honda", b: "Mazda", c: "Toyota", d: "Nissan" },
            answer: "c",
            image: "/assets/Quiz/logo/toyota.png",
          },
          {
            q: "This three-pointed star logo belongs to which manufacturer?",
            options: {
              a: "Mercedes-Benz",
              b: "Mitsubishi",
              c: "Subaru",
              d: "Chrysler",
            },
            answer: "a",
            image: "/assets/Quiz/logo/mercedes.png",
          },
          {
            q: "Identify the leading manufacturer of smartphone processors (Snapdragon)",
            options: { a: "Intel", b: "Qualcomm", c: "Apple", d: "MediaTek" },
            answer: "b",
            image: "/assets/Quiz/logo/qualcomm.png",
          },
          {
            q: "Which luxury brand uses a 'Trident' as its logo?",
            options: {
              a: "Maserati",
              b: "Bugatti",
              c: "Alfa Romeo",
              d: "Bentley",
            },
            answer: "a",
            image: "/assets/Quiz/logo/maserati.png",
          },
          {
            q: "Identify the logo of this South Korean tech giant",
            options: { a: "LG", b: "Samsung", c: "Hyundai", d: "Sony" },
            answer: "b",
            image: "/assets/Quiz/logo/samsung.png",
          },
          {
            q: "This logo featuring six stars (the Pleiades) belongs to?",
            options: { a: "Subaru", b: "Volvo", c: "Ford", d: "Polestar" },
            answer: "a",
            image: "/assets/Quiz/logo/subaru.png",
          },
          {
            q: "Identify the brand known for the 'ThinkPad' and 'Yoga' series",
            options: {
              a: "Acer",
              b: "HP",
              c: "Lenovo",
              d: "Microsoft Surface",
            },
            answer: "c",
            image: "/assets/Quiz/logo/lenovo.png",
          },
          {
            q: "Which camera manufacturer uses a red 'L' or a distinctive red dot?",
            options: { a: "Leica", b: "Lumix", c: "Fujifilm", d: "Kodak" },
            answer: "a",
            image: "/assets/Quiz/logo/lecia.png",
          },
          {
            q: "Identify the logo for this high-performance graphics card brand",
            options: {
              a: "Intel Arc",
              b: "AMD Radeon",
              c: "Nvidia GeForce",
              d: "MSI",
            },
            answer: "c",
            image: "/assets/Quiz/logo/geforce.png",
          },
        ],
      },
      {
        quizId: "QD_06",
        category: "Finance and Travel",
        questions: [
          {
            q: "Identify the payment processor",
            options: { a: "Stripe", b: "PayPal", c: "Visa", d: "Mastercard" },
            answer: "b",
            image: "/assets/Quiz/logo/paypal.png",
          },
          {
            q: "Find the credit card network logo",
            options: { a: "Visa", b: "Mastercard", c: "Amex", d: "Discover" },
            answer: "b",
            image: "/assets/Quiz/logo/mastercard.png",
          },
          {
            q: "Identify the crypto platform",
            options: { a: "Binance", b: "Coinbase", c: "Kraken", d: "WazirX" },
            answer: "a",
            image: "/assets/Quiz/logo/binance.png",
          },
          {
            q: "This logo belongs to which Indian brand?",
            options: {
              a: "Indian Railways",
              b: "State Bank of India",
              c: "LIC",
              d: "Air India",
            },
            answer: "b",
            image: "/assets/Quiz/logo/sbi.png",
          },
          {
            q: "Identify the travel booking app",
            options: { a: "Goibibo", b: "MakeMyTrip", c: "Yatra", d: "Airbnb" },
            answer: "b",
            image: "/assets/Quiz/logo/makemytrip.png",
          },
          {
            q: "Which app uses a 'homestyle' logo for rentals?",
            options: {
              a: "Expedia",
              b: "Trivago",
              c: "Airbnb",
              d: "Booking.com",
            },
            answer: "c",
            image: "/assets/Quiz/logo/airbnb.png",
          },
          {
            q: "Identify the cryptocurrency with the 'diamond' or 'gem' shaped logo",
            options: {
              a: "Bitcoin",
              b: "Ethereum",
              c: "Litecoin",
              d: "Cardano",
            },
            answer: "b",
            image: "/assets/Quiz/logo/ethereum.png",
          },
          {
            q: "Which airline uses a 'Kangaroo' as its iconic logo?",
            options: {
              a: "Air New Zealand",
              b: "Singapore Airlines",
              c: "Qantas",
              d: "Lufthansa",
            },
            answer: "c",
            image: "/assets/Quiz/logo/qantas.png",
          },
          {
            q: "Which card brand’s logo is often associated with bank debit cards and features two overlapping circles in red and blue?",
            options: {
              a: "Visa",
              b: "Maestro",
              c: "RuPay",
              d: "UnionPay",
            },
            answer: "b",
            image: "/assets/Quiz/logo/maestro.png",
          },
          {
            q: "Which investment giant uses a 'Bull' in its branding?",
            options: {
              a: "Merrill Lynch",
              b: "Goldman Sachs",
              c: "Morgan Stanley",
              d: "JP Morgan",
            },
            answer: "a",
            image: "/assets/Quiz/logo/merrill_lynch.png",
          },
          {
            q: "Identify the European airline with the 'Crowned Crane' logo",
            options: {
              a: "KLM",
              b: "Air France",
              c: "Lufthansa",
              d: "Swiss Air",
            },
            answer: "c",
            image: "/assets/Quiz/logo/lufthansa.png",
          },
          {
            q: "Which digital bank or fintech app uses a minimalist 'M' logo?",
            options: { a: "Monzo", b: "Revolut", c: "N26", d: "Starling" },
            answer: "a",
            image: "/assets/Quiz/logo/monzo.png",
          },
          {
            q: "Identify the logo of the world's largest hotel search engine",
            options: {
              a: "Trivago",
              b: "Expedia",
              c: "KAYAK",
              d: "TripAdvisor",
            },
            answer: "a",
            image: "/assets/Quiz/logo/trivago.png",
          },
          {
            q: "Which airline is famous for its 'Red Maple Leaf' tail logo?",
            options: {
              a: "Swiss",
              b: "Air Canada",
              c: "Japan Airlines",
              d: "Austrian Airlines",
            },
            answer: "b",
            image: "/assets/Quiz/logo/air canada.png",
          },
          {
            q: "Which financial services company’s logo features a green torch symbol?",
            options: {
              a: "Fidelity",
              b: "Vanguard",
              c: "BlackRock",
              d: "T. Rowe Price",
            },
            answer: "a",
            image: "/assets/Quiz/logo/fidelity.png",
          },

          {
            q: "This blue 'owl' logo belongs to which travel review site?",
            options: {
              a: "Yelp",
              b: "TripAdvisor",
              c: "Booking.com",
              d: "Agoda",
            },
            answer: "b",
            image: "/assets/Quiz/logo/tripadvisor.png",
          },
        ],
      },
    ],
  },
  {
    _id: "MQZ_NEW_001",
    title: "Music",
    category: [
      {
        quizId: "QD_TS_1",
        category: "Taylor Swift",
        questions: [
          {
            q: "Taylor Swift started her music career mainly in which genre?",
            options: { a: "Rock", b: "Pop", c: "Country", d: "Jazz" },
            answer: "c",
          },
          {
            q: "Which Taylor Swift album is known for storytelling songs like 'Love Story'?",
            options: {
              a: "Reputation",
              b: "Fearless",
              c: "1989",
              d: "Midnights",
            },
            answer: "b",
          },
          {
            q: "What does Taylor Swift love to include in her songs?",
            options: {
              a: "Math formulas",
              b: "Personal stories",
              c: "Science facts",
              d: "Sports rules",
            },
            answer: "b",
          },
          {
            q: "Taylor Swift is famous for writing most of her...",
            options: {
              a: "Dance steps",
              b: "Song lyrics",
              c: "Concert lights",
              d: "Costumes",
            },
            answer: "b",
          },
          {
            q: "What animal is often linked with Taylor Swift’s fan culture?",
            options: { a: "Lion", b: "Snake", c: "Horse", d: "Panda" },
            answer: "b",
          },
        ],
      },
      {
        quizId: "QD_KP_2",
        category: "K-POP World",
        questions: [
          {
            q: "What does K-Pop stand for?",
            options: {
              a: "Kids Pop",
              b: "Korean Popular Music",
              c: "Karaoke Pop",
              d: "Kingdom Pop",
            },
            answer: "b",
          },
          {
            q: "Which country did K-Pop originate from?",
            options: {
              a: "Japan",
              b: "China",
              c: "South Korea",
              d: "Thailand",
            },
            answer: "c",
          },
          {
            q: "K-Pop groups are famous for which combination?",
            options: {
              a: "Only singing",
              b: "Singing + Dancing + Fashion",
              c: "Only rap",
              d: "Only acting",
            },
            answer: "b",
          },
          {
            q: "BTS fans are called?",
            options: { a: "Stars", b: "Army", c: "Beats", d: "Lights" },
            answer: "b",
          },
          {
            q: "BLACKPINK has how many members?",
            options: { a: "3", b: "4", c: "5", d: "7" },
            answer: "b",
          },
        ],
      },
      {
        quizId: "QD_BE_3",
        category: "Billie Eilish",
        questions: [
          {
            q: "At what age did Billie Eilish release her breakout hit 'Ocean Eyes'?",
            options: {
              a: "13 years old",
              b: "19 years old",
              c: "22 years old",
              d: "25 years old",
            },
            answer: "a",
          },
          {
            q: "Which song made Billie Eilish globally famous?",
            options: { a: "Bad Guy", b: "Hello", c: "Roar", d: "Perfect" },
            answer: "a",
          },
          {
            q: "Billie Eilish is known for which style?",
            options: {
              a: "Loud classical music",
              b: "Soft, whisper-style singing",
              c: "Opera singing",
              d: "Folk music",
            },
            answer: "b",
          },
          {
            q: "Billie often wears oversized clothes because she believes in...",
            options: {
              a: "Fashion rules",
              b: "Comfort and self-expression",
              c: "Hiding talent",
              d: "Matching colors",
            },
            answer: "b",
          },
          {
            q: "Who helps Billie Eilish create most of her music?",
            options: {
              a: "Her teacher",
              b: "Her brother Finneas",
              c: "A big band",
              d: "Her fans",
            },
            answer: "b",
          },
        ],
      },
    ],
  },
];
