import { WordsQuestType } from "@/types/adda/game/wordsQuestTypes";

export const WORDS_QUEST: WordsQuestType[] = [
  {
    title: "Find The 10 Positive words",
    fixedBoard: [
      ["F", "Y", "V", "E", "E", "D", "K", "I", "N", "D", "N", "F", "A"],
      ["C", "M", "B", "Y", "R", "Q", "L", "X", "L", "Z", "G", "M", "Q"],
      ["R", "Z", "O", "S", "J", "T", "Q", "K", "J", "U", "T", "R", "X"],
      ["M", "L", "D", "O", "P", "U", "H", "B", "E", "D", "I", "Q", "T"],
      ["W", "V", "W", "U", "R", "Q", "R", "E", "S", "U", "L", "T", "S"],
      ["I", "N", "S", "L", "Y", "Y", "B", "F", "A", "S", "A", "Z", "H"],
      ["S", "C", "Z", "M", "B", "B", "Y", "H", "T", "L", "O", "F", "A"],
      ["H", "Q", "Y", "A", "N", "S", "D", "Z", "O", "N", "I", "R", "R"],
      ["I", "R", "E", "T", "M", "F", "L", "I", "K", "E", "B", "N", "E"],
      ["N", "S", "S", "E", "D", "Z", "B", "F", "J", "Y", "A", "P", "G"],
      ["G", "H", "X", "R", "Q", "T", "R", "E", "V", "I", "V", "E", "F"],
      ["F", "L", "O", "V", "E", "U", "P", "O", "T", "V", "K", "I", "W"],
      ["X", "B", "T", "K", "M", "U", "N", "E", "V", "N", "Q", "X", "I"],
      ["M", "G", "C", "N", "P", "J", "X", "R", "L", "A", "P", "P", "S"],
    ],
    wordsToFind: [
      "KIND",
      "LOVE",
      "REVIVE",
      "WISHING",
      "SOULMATE",
      "RESULTS",
      "SHARE",
      "LIKE",
      "APPS",
      "HEALING",
    ],
    bg: "/assets/games/wordsQuest/BG 1.png",
  },
  {
    title: "Can you Find All 10 Relationship Terms?",
    fixedBoard: [
      ["F", "Y", "V", "E", "O", "R", "B", "I", "T", "I", "N", "G", "G"],
      ["C", "F", "B", "Y", "R", "Q", "L", "X", "L", "Z", "S", "M", "Q"],
      ["B", "R", "E", "A", "D", "C", "R", "U", "M", "B", "I", "N", "G"],
      ["M", "I", "D", "G", "P", "A", "Q", "L", "E", "D", "T", "Q", "T"],
      ["Z", "E", "W", "A", "R", "T", "F", "O", "G", "X", "U", "T", "R"],
      ["L", "N", "S", "S", "Y", "F", "B", "V", "H", "S", "A", "Z", "E"],
      ["M", "D", "Z", "L", "B", "I", "Y", "E", "O", "F", "T", "F", "D"],
      ["C", "Z", "Y", "I", "N", "S", "D", "B", "S", "N", "I", "R", "F"],
      ["H", "O", "E", "G", "M", "H", "N", "O", "T", "K", "O", "A", "L"],
      ["Q", "N", "S", "H", "D", "I", "B", "M", "I", "Y", "N", "P", "A"],
      ["R", "E", "S", "T", "Q", "N", "T", "B", "N", "T", "S", "Q", "G"],
      ["F", "S", "V", "I", "K", "G", "P", "I", "G", "V", "H", "I", "W"],
      ["X", "B", "T", "N", "M", "B", "E", "N", "C", "H", "I", "N", "G"],
      ["M", "G", "C", "G", "P", "J", "X", "G", "L", "I", "P", "X", "R"],
    ],
    wordsToFind: [
      "ORBITING",
      "BREADCRUMBING",
      "BENCHING",
      "GASLIGHTING",
      "LOVEBOMBING",
      "SITUATIONSHIP",
      "GHOSTING",
      "CATFISHING",
      "FRIENDZONE",
      "REDFLAG",
    ],
    bg: "/assets/games/wordsQuest/BG 2.png",
  },
  {
    title: "Can You Find All 10 Social Media Buzzwords?",
    fixedBoard: [
      ["F", "P", "R", "O", "F", "I", "L", "E", "D", "T", "I", "F", "G"],
      ["C", "Y", "B", "Y", "R", "Q", "L", "X", "L", "Z", "N", "M", "V"],
      ["R", "V", "O", "M", "F", "J", "Q", "K", "J", "U", "F", "R", "I"],
      ["M", "E", "T", "O", "O", "O", "Y", "I", "Z", "D", "L", "Q", "R"],
      ["Q", "D", "W", "R", "R", "E", "L", "F", "B", "P", "U", "T", "A"],
      ["T", "N", "S", "Q", "E", "Y", "B", "L", "J", "S", "E", "Z", "L"],
      ["E", "R", "Z", "L", "B", "N", "Y", "H", "O", "B", "N", "F", "E"],
      ["F", "E", "Y", "B", "N", "S", "D", "Z", "O", "W", "C", "R", "N"],
      ["T", "P", "E", "E", "M", "F", "K", "I", "M", "U", "E", "I", "S"],
      ["C", "O", "S", "Q", "D", "Z", "B", "F", "N", "Y", "R", "R", "T"],
      ["R", "S", "S", "H", "A", "S", "H", "T", "A", "G", "T", "X", "S"],
      ["F", "T", "N", "P", "X", "U", "P", "O", "T", "R", "V", "N", "W"],
      ["X", "B", "T", "A", "L", "G", "O", "R", "I", "T", "H", "M", "I"],
      ["C", "O", "N", "T", "E", "N", "T", "X", "C", "L", "K", "X", "R"],
    ],
    wordsToFind: [
      "PROFILE",
      "METOO",
      "VIRAL",
      "REPOST",
      "HASHTAG",
      "ALGORITHM",
      "CONTENT",
      "INFLUENCER",
      "FOLLOWER",
      "TRENDING",
    ],
    bg: "/assets/games/wordsQuest/BG 3.png",
  },
  {
    title: "can you Find All 10 Chat Shortcuts?",
    fixedBoard: [
      ["F", "Y", "V", "E", "E", "D", "L", "R", "T", "H", "N", "F", "V"],
      ["C", "R", "B", "G", "R", "W", "M", "X", "L", "Z", "G", "M", "Y"],
      ["R", "I", "O", "M", "J", "Y", "Q", "K", "J", "U", "T", "R", "I"],
      ["M", "Y", "D", "Z", "D", "Q", "E", "Z", "O", "G", "O", "A", "T"],
      ["Q", "K", "W", "N", "R", "P", "O", "V", "B", "P", "V", "T", "W"],
      ["T", "Y", "S", "Q", "Y", "N", "B", "F", "J", "S", "Z", "D", "L"],
      ["Q", "K", "Z", "L", "B", "F", "Y", "H", "N", "B", "O", "F", "E"],
      ["Y", "C", "Y", "B", "F", "S", "D", "Z", "G", "N", "C", "R", "N"],
      ["F", "R", "E", "E", "O", "F", "I", "M", "L", "D", "T", "I", "S"],
      ["L", "S", "S", "Q", "M", "Z", "B", "F", "J", "Y", "A", "P", "T"],
      ["M", "H", "R", "M", "O", "F", "T", "Q", "R", "U", "T", "X", "F"],
      ["A", "V", "N", "P", "X", "U", "P", "O", "T", "B", "R", "B", "W"],
      ["O", "B", "T", "O", "M", "G", "N", "E", "V", "N", "Q", "X", "I"],
      ["E", "G", "C", "X", "U", "L", "K", "S", "M", "H", "K", "X", "R"],
    ],
    wordsToFind: [
      "IYKYK",
      "GRWM",
      "GOAT",
      "POV",
      "NGL",
      "FOMO",
      "LMAO",
      "OMG",
      "BRB",
      "SMH",
    ],
    bg: "/assets/games/wordsQuest/BG 4.png",
  },
  {
    title: "Find The 10 Positive words",
    fixedBoard: [
      ["F", "P", "R", "O", "F", "I", "L", "E", "D", "T", "I", "F", "G"],
      ["C", "Y", "B", "Y", "R", "Q", "L", "X", "L", "Z", "N", "M", "V"],
      ["R", "V", "O", "M", "F", "J", "Q", "K", "J", "U", "F", "R", "I"],
      ["M", "E", "T", "O", "O", "O", "Y", "I", "Z", "D", "L", "Q", "R"],
      ["Q", "D", "W", "R", "R", "E", "L", "F", "B", "P", "U", "T", "A"],
      ["T", "N", "S", "Q", "E", "Y", "B", "L", "J", "S", "E", "Z", "L"],
      ["E", "R", "Z", "L", "B", "N", "Y", "H", "O", "B", "N", "F", "E"],
      ["F", "E", "Y", "B", "N", "S", "D", "Z", "O", "W", "C", "R", "N"],
      ["T", "P", "E", "E", "M", "F", "K", "I", "M", "U", "E", "I", "S"],
      ["C", "O", "S", "Q", "D", "Z", "B", "F", "N", "Y", "R", "R", "T"],
      ["R", "S", "S", "H", "A", "S", "H", "T", "A", "G", "T", "X", "S"],
      ["F", "T", "N", "P", "X", "U", "P", "O", "T", "R", "V", "N", "W"],
      ["X", "B", "T", "A", "L", "G", "O", "R", "I", "T", "H", "M", "I"],
      ["C", "O", "N", "T", "E", "N", "T", "X", "C", "L", "K", "X", "R"],
    ],
    wordsToFind: [
      "KIND",
      "LOVE",
      "REVIVE",
      "WISHING",
      "SOULMATE",
      "RESULTS",
      "SHARE",
      "LIKE",
      "APPS",
      "HEALING",
    ],
    bg: "/assets/games/wordsQuest/BG 1.png",
  },
  {
    title: "Find The 10 Positive words",
    fixedBoard: [
      ["F", "Y", "V", "E", "E", "D", "K", "I", "N", "D", "N", "F", "A"],
      ["C", "M", "B", "Y", "R", "Q", "L", "X", "L", "Z", "G", "M", "Q"],
      ["R", "Z", "O", "S", "J", "T", "Q", "K", "J", "U", "T", "R", "X"],
      ["M", "L", "D", "O", "P", "U", "H", "B", "E", "D", "I", "Q", "T"],
      ["W", "V", "W", "U", "R", "Q", "R", "E", "S", "U", "L", "T", "S"],
      ["I", "N", "S", "L", "Y", "Y", "B", "F", "A", "S", "A", "Z", "H"],
      ["S", "C", "Z", "M", "B", "B", "Y", "H", "T", "L", "O", "F", "A"],
      ["H", "Q", "Y", "A", "N", "S", "D", "Z", "O", "N", "I", "R", "R"],
      ["I", "R", "E", "T", "M", "F", "L", "I", "K", "E", "B", "N", "E"],
      ["N", "S", "S", "E", "D", "Z", "B", "F", "J", "Y", "A", "P", "G"],
      ["G", "H", "X", "R", "Q", "T", "R", "E", "V", "I", "V", "E", "F"],
      ["F", "L", "O", "V", "E", "U", "P", "O", "T", "V", "K", "I", "W"],
      ["X", "B", "T", "K", "M", "U", "N", "E", "V", "N", "Q", "X", "I"],
      ["M", "G", "C", "N", "P", "J", "X", "R", "L", "A", "P", "P", "S"],
    ],
    wordsToFind: [
      "KIND",
      "LOVE",
      "REVIVE",
      "WISHING",
      "SOULMATE",
      "RESULTS",
      "SHARE",
      "LIKE",
      "APPS",
      "HEALING",
    ],
    bg: "/assets/games/wordsQuest/BG 1.png",
  },
  {
    title: "Find The 10 Positive words",
    fixedBoard: [
      ["F", "Y", "V", "E", "E", "D", "K", "I", "N", "D", "N", "F", "A"],
      ["C", "M", "B", "Y", "R", "Q", "L", "X", "L", "Z", "G", "M", "Q"],
      ["R", "Z", "O", "S", "J", "T", "Q", "K", "J", "U", "T", "R", "X"],
      ["M", "L", "D", "O", "P", "U", "H", "B", "E", "D", "I", "Q", "T"],
      ["W", "V", "W", "U", "R", "Q", "R", "E", "S", "U", "L", "T", "S"],
      ["I", "N", "S", "L", "Y", "Y", "B", "F", "A", "S", "A", "Z", "H"],
      ["S", "C", "Z", "M", "B", "B", "Y", "H", "T", "L", "O", "F", "A"],
      ["H", "Q", "Y", "A", "N", "S", "D", "Z", "O", "N", "I", "R", "R"],
      ["I", "R", "E", "T", "M", "F", "L", "I", "K", "E", "B", "N", "E"],
      ["N", "S", "S", "E", "D", "Z", "B", "F", "J", "Y", "A", "P", "G"],
      ["G", "H", "X", "R", "Q", "T", "R", "E", "V", "I", "V", "E", "F"],
      ["F", "L", "O", "V", "E", "U", "P", "O", "T", "V", "K", "I", "W"],
      ["X", "B", "T", "K", "M", "U", "N", "E", "V", "N", "Q", "X", "I"],
      ["M", "G", "C", "N", "P", "J", "X", "R", "L", "A", "P", "P", "S"],
    ],
    wordsToFind: [
      "KIND",
      "LOVE",
      "REVIVE",
      "WISHING",
      "SOULMATE",
      "RESULTS",
      "SHARE",
      "LIKE",
      "APPS",
      "HEALING",
    ],
    bg: "/assets/games/wordsQuest/BG 1.png",
  },
  {
    title: "Find The 10 Positive words",
    fixedBoard: [
      ["F", "Y", "V", "E", "E", "D", "K", "I", "N", "D", "N", "F", "A"],
      ["C", "M", "B", "Y", "R", "Q", "L", "X", "L", "Z", "G", "M", "Q"],
      ["R", "Z", "O", "S", "J", "T", "Q", "K", "J", "U", "T", "R", "X"],
      ["M", "L", "D", "O", "P", "U", "H", "B", "E", "D", "I", "Q", "T"],
      ["W", "V", "W", "U", "R", "Q", "R", "E", "S", "U", "L", "T", "S"],
      ["I", "N", "S", "L", "Y", "Y", "B", "F", "A", "S", "A", "Z", "H"],
      ["S", "C", "Z", "M", "B", "B", "Y", "H", "T", "L", "O", "F", "A"],
      ["H", "Q", "Y", "A", "N", "S", "D", "Z", "O", "N", "I", "R", "R"],
      ["I", "R", "E", "T", "M", "F", "L", "I", "K", "E", "B", "N", "E"],
      ["N", "S", "S", "E", "D", "Z", "B", "F", "J", "Y", "A", "P", "G"],
      ["G", "H", "X", "R", "Q", "T", "R", "E", "V", "I", "V", "E", "F"],
      ["F", "L", "O", "V", "E", "U", "P", "O", "T", "V", "K", "I", "W"],
      ["X", "B", "T", "K", "M", "U", "N", "E", "V", "N", "Q", "X", "I"],
      ["M", "G", "C", "N", "P", "J", "X", "R", "L", "A", "P", "P", "S"],
    ],
    wordsToFind: [
      "KIND",
      "LOVE",
      "REVIVE",
      "WISHING",
      "SOULMATE",
      "RESULTS",
      "SHARE",
      "LIKE",
      "APPS",
      "HEALING",
    ],
    bg: "/assets/games/wordsQuest/BG 1.png",
  },
  {
    title: "Find The 10 Positive words",
    fixedBoard: [
      ["F", "Y", "V", "E", "E", "D", "K", "I", "N", "D", "N", "F", "A"],
      ["C", "M", "B", "Y", "R", "Q", "L", "X", "L", "Z", "G", "M", "Q"],
      ["R", "Z", "O", "S", "J", "T", "Q", "K", "J", "U", "T", "R", "X"],
      ["M", "L", "D", "O", "P", "U", "H", "B", "E", "D", "I", "Q", "T"],
      ["W", "V", "W", "U", "R", "Q", "R", "E", "S", "U", "L", "T", "S"],
      ["I", "N", "S", "L", "Y", "Y", "B", "F", "A", "S", "A", "Z", "H"],
      ["S", "C", "Z", "M", "B", "B", "Y", "H", "T", "L", "O", "F", "A"],
      ["H", "Q", "Y", "A", "N", "S", "D", "Z", "O", "N", "I", "R", "R"],
      ["I", "R", "E", "T", "M", "F", "L", "I", "K", "E", "B", "N", "E"],
      ["N", "S", "S", "E", "D", "Z", "B", "F", "J", "Y", "A", "P", "G"],
      ["G", "H", "X", "R", "Q", "T", "R", "E", "V", "I", "V", "E", "F"],
      ["F", "L", "O", "V", "E", "U", "P", "O", "T", "V", "K", "I", "W"],
      ["X", "B", "T", "K", "M", "U", "N", "E", "V", "N", "Q", "X", "I"],
      ["M", "G", "C", "N", "P", "J", "X", "R", "L", "A", "P", "P", "S"],
    ],
    wordsToFind: [
      "KIND",
      "LOVE",
      "REVIVE",
      "WISHING",
      "SOULMATE",
      "RESULTS",
      "SHARE",
      "LIKE",
      "APPS",
      "HEALING",
    ],
    bg: "/assets/games/wordsQuest/BG 1.png",
  },
  {
    title: "Find The 10 Positive words",
    fixedBoard: [
      ["F", "Y", "V", "E", "E", "D", "K", "I", "N", "D", "N", "F", "A"],
      ["C", "M", "B", "Y", "R", "Q", "L", "X", "L", "Z", "G", "M", "Q"],
      ["R", "Z", "O", "S", "J", "T", "Q", "K", "J", "U", "T", "R", "X"],
      ["M", "L", "D", "O", "P", "U", "H", "B", "E", "D", "I", "Q", "T"],
      ["W", "V", "W", "U", "R", "Q", "R", "E", "S", "U", "L", "T", "S"],
      ["I", "N", "S", "L", "Y", "Y", "B", "F", "A", "S", "A", "Z", "H"],
      ["S", "C", "Z", "M", "B", "B", "Y", "H", "T", "L", "O", "F", "A"],
      ["H", "Q", "Y", "A", "N", "S", "D", "Z", "O", "N", "I", "R", "R"],
      ["I", "R", "E", "T", "M", "F", "L", "I", "K", "E", "B", "N", "E"],
      ["N", "S", "S", "E", "D", "Z", "B", "F", "J", "Y", "A", "P", "G"],
      ["G", "H", "X", "R", "Q", "T", "R", "E", "V", "I", "V", "E", "F"],
      ["F", "L", "O", "V", "E", "U", "P", "O", "T", "V", "K", "I", "W"],
      ["X", "B", "T", "K", "M", "U", "N", "E", "V", "N", "Q", "X", "I"],
      ["M", "G", "C", "N", "P", "J", "X", "R", "L", "A", "P", "P", "S"],
    ],
    wordsToFind: [
      "KIND",
      "LOVE",
      "REVIVE",
      "WISHING",
      "SOULMATE",
      "RESULTS",
      "SHARE",
      "LIKE",
      "APPS",
      "HEALING",
    ],
    bg: "/assets/games/wordsQuest/BG 1.png",
  },
];
