import { WordsQuestType } from "@/types/adda/game/wordsQuestTypes";

export const WORDS_QUEST: WordsQuestType = {
  easy: [
    {
      title: "Inside My House! Find the 10 Things!",
      fixedBoard: [
        ["F", "Y", "B", "A", "L", "C", "O", "N", "Y", "B", "R", "L", "X"],
        ["C", "B", "E", "M", "V", "Y", "A", "X", "M", "Z", "G", "M", "Q"],
        ["R", "S", "C", "T", "E", "L", "E", "V", "I", "S", "I", "O", "N"],
        ["M", "D", "A", "Z", "P", "J", "U", "B", "R", "D", "K", "Q", "T"],
        ["Y", "V", "R", "L", "B", "Q", "S", "Y", "R", "T", "K", "S", "U"],
        ["Q", "N", "P", "D", "P", "I", "L", "L", "O", "W", "S", "O", "R"],
        ["U", "C", "E", "Z", "W", "T", "B", "H", "R", "F", "O", "F", "N"],
        ["Z", "Q", "T", "Y", "S", "L", "D", "A", "O", "N", "F", "A", "Z"],
        ["W", "R", "H", "W", "D", "F", "E", "F", "T", "Z", "B", "K", "Y"],
        ["S", "I", "P", "S", "X", "D", "O", "O", "R", "B", "E", "L", "L"],
        ["V", "H", "N", "R", "C", "L", "O", "C", "K", "I", "Q", "I", "F"],
        ["Z", "X", "U", "D", "Q", "T", "R", "O", "R", "V", "D", "K", "W"],
        ["F", "B", "T", "K", "O", "U", "N", "E", "V", "N", "Q", "G", "U"],
        ["B", "G", "C", "X", "P", "W", "M", "R", "L", "J", "Y", "X", "E"],
      ],
      wordsToFind: [
        "SOFA",
        "TELEVISION",
        "FRIDGE",
        "WINDOW",
        "CLOCK",
        "PILLOW",
        "MIRROR",
        "DOORBELL",
        "CARPET",
        "BALCONY",
      ],
      bg: "/assets/games/wordsQuest/BG 1.png",
    },
    {
      title: "Find The 10 Positive Words",
      fixedBoard: [
        ["F", "Y", "V", "E", "E", "D", "K", "I", "N", "D", "N", "F", "P"],
        ["C", "W", "B", "Y", "R", "Q", "L", "X", "L", "Z", "G", "M", "E"],
        ["R", "I", "O", "M", "J", "L", "Q", "K", "J", "U", "T", "R", "A"],
        ["M", "S", "D", "Z", "H", "A", "P", "P", "Y", "D", "I", "Q", "C"],
        ["Q", "H", "W", "N", "R", "U", "Y", "F", "B", "P", "V", "T", "E"],
        ["T", "I", "S", "Q", "Y", "G", "B", "F", "J", "S", "A", "Z", "D"],
        ["J", "N", "Z", "L", "B", "H", "Y", "H", "T", "B", "O", "F", "E"],
        ["O", "G", "Y", "B", "N", "S", "D", "Z", "O", "N", "E", "R", "N"],
        ["Y", "R", "E", "E", "M", "F", "L", "O", "V", "E", "Y", "I", "S"],
        ["C", "S", "S", "Q", "D", "Z", "B", "F", "J", "Y", "A", "P", "T"],
        ["R", "H", "B", "O", "N", "D", "T", "Q", "R", "U", "T", "X", "F"],
        ["F", "V", "N", "P", "X", "U", "P", "O", "T", "H", "U", "G", "W"],
        ["X", "B", "T", "K", "M", "U", "N", "E", "V", "N", "Q", "X", "I"],
        ["M", "G", "C", "S", "M", "I", "L", "E", "S", "L", "K", "X", "R"],
      ],
      wordsToFind: [
        "KIND",
        "PEACE",
        "HAPPY",
        "LAUGH",
        "WISHING",
        "JOY",
        "LOVE",
        "BOND",
        "HUG",
        "SMILES",
      ],
      bg: "/assets/games/wordsQuest/BG 2.png",
    },
    {
      title: "Find the 10 Chocolate Names!",
      fixedBoard: [
        ["F", "P", "V", "E", "F", "I", "V", "E", "S", "T", "A", "R", "A"],
        ["C", "E", "B", "Y", "R", "Q", "L", "X", "L", "Z", "G", "M", "Q"],
        ["R", "R", "O", "M", "J", "S", "B", "O", "U", "N", "T", "Y", "X"],
        ["M", "K", "D", "Z", "P", "U", "N", "B", "E", "D", "I", "Q", "T"],
        ["y", "V", "M", "L", "K", "Q", "S", "I", "T", "Y", "K", "T", "U"],
        ["E", "N", "I", "D", "I", "I", "B", "F", "C", "S", "A", "Z", "R"],
        ["C", "C", "L", "Z", "T", "B", "N", "H", "T", "K", "O", "F", "N"],
        ["L", "Q", "K", "W", "K", "S", "D", "D", "O", "N", "E", "R", "F"],
        ["A", "R", "Y", "Y", "A", "F", "E", "Q", "E", "Z", "B", "R", "Y"],
        ["I", "S", "B", "S", "T", "Z", "B", "F", "J", "R", "A", "P", "S"],
        ["R", "H", "A", "R", "Q", "T", "R", "Y", "F", "O", "J", "I", "F"],
        ["S", "X", "R", "U", "D", "G", "E", "M", "S", "V", "K", "O", "W"],
        ["X", "B", "T", "K", "M", "U", "N", "E", "V", "N", "Q", "X", "Y"],
        ["M", "G", "C", "M", "U", "N", "C", "H", "L", "P", "X", "P", "T"],
      ],
      wordsToFind: [
        "MUNCH",
        "PERK",
        "KITKAT",
        "GEMS",
        "MILKYBAR",
        "KINDERJOY",
        "FIVESTAR",
        "ECLAIRS",
        "SNICKERS",
        "BOUNTY",
      ],
      bg: "/assets/games/wordsQuest/BG 3.png",
    },
    {
      title: "Find The 10 Tasty Foods",
      fixedBoard: [
        ["F", "Z", "V", "E", "Y", "R", "Q", "C", "T", "K", "X", "D", "A"],
        ["C", "M", "B", "B", "U", "R", "G", "E", "R", "Z", "G", "M", "Q"],
        ["R", "T", "O", "M", "J", "Z", "L", "X", "L", "P", "U", "T", "P"],
        ["M", "O", "D", "M", "P", "U", "F", "B", "E", "D", "I", "Q", "I"],
        ["Y", "P", "V", "L", "O", "Q", "S", "R", "T", "Y", "K", "T", "Z"],
        ["N", "O", "Z", "D", "R", "S", "B", "F", "I", "S", "A", "Z", "Z"],
        ["C", "P", "A", "S", "T", "A", "B", "H", "T", "E", "O", "F", "A"],
        ["J", "C", "Q", "Y", "S", "M", "D", "F", "O", "N", "S", "R", "F"],
        ["G", "O", "R", "W", "F", "O", "E", "Q", "N", "Z", "B", "P", "Y"],
        ["S", "R", "Z", "S", "B", "S", "A", "N", "D", "W", "I", "C", "H"],
        ["T", "N", "H", "R", "Q", "A", "R", "Y", "F", "O", "A", "I", "F"],
        ["M", "X", "N", "U", "D", "Q", "N", "E", "V", "V", "K", "X", "W"],
        ["X", "B", "T", "K", "M", "U", "N", "O", "O", "D", "L", "E", "S"],
        ["T", "A", "C", "O", "S", "C", "K", "U", "L", "P", "X", "P", "T"],
      ],
      wordsToFind: [
        "BURGER",
        "PIZZA",
        "SANDWICH",
        "PASTA",
        "NOODLES",
        "FRIES",
        "SAMOSA",
        "POPCORN",
        "TACOS",
        "MOMOS",
      ],
      bg: "/assets/games/wordsQuest/BG 4.png",
    },
    {
      title: "Game on! Find The 10 Gaming Words!",
      fixedBoard: [
        ["F", "Y", "V", "E", "Y", "Q", "L", "A", "S", "T", "A", "R", "T"],
        ["C", "B", "B", "O", "N", "U", "S", "X", "L", "Z", "G", "M", "Q"],
        ["R", "S", "A", "M", "J", "B", "Q", "A", "E", "F", "R", "O", "S"],
        ["M", "D", "T", "Z", "P", "S", "U", "B", "P", "D", "I", "Q", "T"],
        ["Y", "V", "T", "L", "B", "C", "S", "Y", "T", "O", "K", "T", "U"],
        ["Q", "N", "L", "D", "C", "O", "I", "N", "S", "S", "W", "Z", "R"],
        ["U", "C", "E", "Z", "W", "R", "B", "H", "T", "F", "W", "E", "N"],
        ["Z", "Q", "R", "Y", "S", "E", "D", "Q", "O", "N", "O", "R", "R"],
        ["W", "R", "H", "W", "D", "F", "E", "Q", "U", "Z", "F", "K", "Y"],
        ["I", "S", "P", "S", "S", "Z", "B", "F", "J", "E", "B", "P", "T"],
        ["N", "H", "V", "R", "Q", "T", "R", "Y", "F", "O", "S", "I", "F"],
        ["N", "X", "U", "L", "E", "V", "E", "L", "R", "V", "S", "T", "W"],
        ["E", "B", "T", "K", "M", "U", "N", "E", "V", "N", "Q", "X", "U"],
        ["R", "G", "C", "X", "P", "L", "M", "P", "L", "A", "Y", "E", "R"],
      ],
      wordsToFind: [
        "PLAYER",
        "LEVEL",
        "START",
        "SCORE",
        "WINNER",
        "BONUS",
        "POWER",
        "QUEST",
        "COINS",
        "BATTLE",
      ],
      bg: "/assets/games/wordsQuest/BG 1.png",
    },
    {
      title: "Sweet Time! Find The 10 Sweet Treats!",
      fixedBoard: [
        ["F", "C", "V", "E", "B", "R", "O", "W", "N", "I", "E", "T", "A"],
        ["C", "A", "B", "Y", "R", "Q", "L", "X", "L", "Z", "G", "M", "Q"],
        ["R", "K", "O", "M", "J", "H", "C", "O", "O", "K", "I", "E", "X"],
        ["M", "E", "D", "Z", "P", "U", "S", "B", "E", "D", "I", "Q", "I"],
        ["Y", "V", "Y", "L", "D", "Q", "C", "F", "T", "Y", "K", "T", "C"],
        ["S", "N", "P", "D", "O", "U", "B", "A", "N", "S", "A", "Z", "E"],
        ["M", "C", "H", "Z", "N", "B", "R", "H", "N", "T", "O", "F", "C"],
        ["U", "Q", "E", "Y", "U", "S", "D", "Q", "O", "D", "N", "R", "R"],
        ["F", "R", "D", "W", "T", "F", "J", "E", "L", "L", "Y", "F", "E"],
        ["F", "H", "B", "R", "Q", "T", "R", "Y", "F", "O", "Z", "I", "A"],
        ["I", "X", "F", "U", "D", "V", "H", "A", "L", "W", "A", "F", "M"],
        ["N", "B", "T", "K", "M", "U", "N", "E", "V", "N", "Q", "X", "W"],
        ["X", "B", "T", "K", "M", "U", "N", "E", "V", "N", "Q", "X", "K"],
        ["M", "G", "C", "L", "A", "D", "D", "U", "L", "P", "X", "P", "T"],
      ],
      wordsToFind: [
        "CAKE",
        "DONUT",
        "ICECREAM",
        "BROWNIE",
        "COOKIE",
        "CANDY",
        "JELLY",
        "MUFFIN",
        "LADDU",
        "HALWA",
      ],
      bg: "/assets/games/wordsQuest/BG 2.png",
    },
    {
      title: "Hero Mode On! Find the 10 Superheroes!",
      fixedBoard: [
        ["F", "Z", "V", "E", "Y", "R", "Q", "C", "T", "C", "X", "D", "A"],
        ["C", "M", "B", "O", "K", "B", "A", "T", "M", "A", "N", "M", "Q"],
        ["R", "T", "D", "M", "J", "Z", "L", "X", "L", "P", "U", "T", "Z"],
        ["S", "P", "I", "D", "E", "R", "M", "A", "N", "T", "I", "Q", "G"],
        ["Y", "P", "V", "L", "D", "Q", "S", "F", "L", "A", "S", "H", "K"],
        ["N", "S", "U", "P", "E", "R", "M", "A", "N", "I", "A", "Z", "T"],
        ["I", "F", "A", "C", "R", "Y", "B", "H", "T", "N", "O", "F", "D"],
        ["R", "J", "Q", "Q", "S", "U", "D", "S", "O", "A", "B", "R", "F"],
        ["O", "F", "R", "W", "U", "Y", "E", "H", "N", "M", "B", "P", "T"],
        ["N", "G", "Z", "S", "B", "A", "F", "A", "B", "E", "Q", "Z", "H"],
        ["M", "S", "H", "R", "Q", "T", "M", "Z", "F", "R", "A", "I", "O"],
        ["A", "X", "N", "U", "D", "Q", "N", "A", "V", "I", "K", "X", "R"],
        ["N", "B", "T", "K", "M", "U", "T", "M", "N", "C", "P", "E", "Z"],
        ["X", "C", "H", "U", "L", "K", "K", "U", "L", "A", "X", "P", "T"],
      ],
      wordsToFind: [
        "SPIDERMAN",
        "SUPERMAN",
        "BATMAN",
        "IRONMAN",
        "FLASH",
        "AQUAMAN",
        "CAPTAINAMERICA",
        "HULK",
        "THOR",
        "SHAZAM",
      ],
      bg: "/assets/games/wordsQuest/BG 3.png",
    },
    {
      title: "Music Mania! Find the 10 instruments",
      fixedBoard: [
        ["F", "B", "V", "E", "P", "R", "Z", "A", "F", "L", "U", "T", "E"],
        ["G", "U", "I", "T", "A", "R", "L", "X", "L", "Z", "G", "M", "Q"],
        ["R", "C", "O", "M", "J", "Y", "Q", "B", "E", "D", "Q", "V", "X"],
        ["M", "K", "D", "K", "A", "L", "I", "M", "B", "A", "I", "I", "T"],
        ["Y", "V", "T", "L", "T", "Q", "S", "R", "P", "Y", "K", "O", "U"],
        ["Z", "D", "N", "D", "S", "U", "B", "I", "F", "I", "A", "L", "R"],
        ["C", "R", "S", "Z", "I", "B", "H", "D", "T", "F", "A", "I", "N"],
        ["J", "U", "Q", "Y", "T", "S", "D", "A", "O", "N", "O", "N", "F"],
        ["R", "M", "R", "W", "A", "F", "E", "N", "Q", "Z", "B", "R", "O"],
        ["S", "S", "T", "S", "R", "Z", "B", "G", "J", "F", "X", "P", "Y"],
        ["W", "H", "Y", "R", "Q", "T", "R", "A", "F", "O", "K", "I", "F"],
        ["G", "X", "D", "U", "H", "A", "R", "M", "O", "N", "I", "C", "A"],
        ["X", "B", "T", "K", "M", "U", "N", "E", "V", "N", "Q", "X", "W"],
        ["M", "T", "A", "B", "L", "A", "C", "V", "L", "P", "X", "P", "T"],
      ],
      wordsToFind: [
        "GUITAR",
        "PIANO",
        "DRUMS",
        "FLUTE",
        "VIOLIN",
        "TABLA",
        "SITAR",
        "MRIDANGAM",
        "KALIMBA",
        "HARMONICA",
      ],
      bg: "/assets/games/wordsQuest/BG 4.png",
    },
    {
      title: "Weather Watch! Find the 10 Weather Words!",
      fixedBoard: [
        ["F", "E", "V", "E", "S", "U", "N", "N", "Y", "T", "Q", "T", "A"],
        ["C", "C", "B", "Y", "R", "Q", "L", "X", "L", "Z", "G", "S", "Q"],
        ["R", "O", "L", "M", "W", "I", "N", "D", "H", "J", "D", "N", "X"],
        ["M", "Z", "D", "O", "P", "U", "S", "B", "E", "L", "I", "O", "M"],
        ["S", "V", "Y", "L", "U", "Q", "Y", "F", "T", "I", "K", "W", "Y"],
        ["T", "N", "P", "D", "S", "D", "B", "S", "N", "G", "A", "Z", "T"],
        ["O", "H", "H", "Z", "U", "B", "Y", "H", "R", "H", "O", "F", "B"],
        ["R", "Q", "U", "Y", "C", "S", "D", "R", "O", "T", "N", "R", "R"],
        ["M", "R", "D", "N", "W", "F", "T", "A", "Q", "N", "Y", "F", "E"],
        ["D", "S", "Y", "S", "D", "Z", "B", "I", "I", "I", "A", "P", "E"],
        ["F", "H", "B", "R", "Q", "E", "R", "N", "F", "N", "Z", "I", "Z"],
        ["W", "X", "F", "U", "D", "V", "R", "E", "L", "G", "O", "F", "E"],
        ["X", "B", "T", "K", "M", "U", "N", "E", "V", "N", "Q", "X", "K"],
        ["M", "G", "C", "C", "Y", "C", "L", "O", "N", "E", "X", "P", "T"],
      ],
      wordsToFind: [
        "SUNNY",
        "RAIN",
        "CLOUDY",
        "WIND",
        "SNOW",
        "STORM",
        "CYCLONE",
        "THUNDER",
        "LIGHTNING",
        "BREEZE",
      ],
      bg: "/assets/games/wordsQuest/BG 1.png",
    },
    {
      title: "What's in My Bag? Find the 10 Items?",
      fixedBoard: [
        ["F", "O", "V", "E", "M", "T", "O", "W", "E", "L", "H", "T", "P"],
        ["W", "C", "B", "Y", "R", "Q", "L", "X", "L", "Z", "G", "M", "E"],
        ["A", "R", "L", "U", "N", "C", "H", "B", "O", "X", "Z", "J", "N"],
        ["L", "M", "D", "M", "P", "U", "S", "B", "E", "D", "I", "Q", "C"],
        ["L", "V", "Y", "B", "Y", "Q", "L", "F", "T", "Y", "K", "T", "I"],
        ["E", "N", "P", "R", "D", "I", "D", "C", "A", "R", "D", "Z", "L"],
        ["T", "C", "H", "E", "Z", "B", "I", "H", "Y", "T", "O", "F", "B"],
        ["S", "S", "E", "L", "Q", "S", "A", "B", "O", "X", "N", "R", "O"],
        ["W", "R", "N", "L", "D", "F", "R", "R", "O", "U", "B", "F", "X"],
        ["S", "S", "Y", "A", "D", "Z", "Y", "F", "J", "T", "A", "P", "Q"],
        ["N", "H", "B", "R", "C", "T", "R", "Y", "F", "O", "T", "I", "E"],
        ["K", "X", "F", "U", "D", "K", "T", "U", "V", "F", "B", "L", "W"],
        ["X", "B", "B", "O", "O", "K", "S", "E", "V", "N", "Q", "X", "E"],
        ["M", "G", "C", "K", "A", "M", "S", "N", "L", "P", "X", "P", "T"],
      ],
      wordsToFind: [
        "LUNCHBOX",
        "BOTTLE",
        "TOWEL",
        "SNACKS",
        "DIARY",
        "IDCARD",
        "PENCILBOX",
        "BOOKS",
        "UMBRELLA",
        "WALLET",
      ],
      bg: "/assets/games/wordsQuest/BG 2.png",
    },
  ],
  medium: [
    {
      title: "Find The 10 Positive words",
      fixedBoard: [
        ["F", "Y", "V", "E", "E", "D", "K", "I", "N", "D", "N", "F", "A"],
        ["C", "M", "B", "Y", "R", "Q", "L", "X", "L", "Z", "G", "M", "Q"],
        ["R", "Z", "O", "S", "J", "T", "Q", "K", "J", "U", "T", "R", "X"],
        ["M", "L", "D", "O", "P", "U", "H", "B", "E", "D", "I", "Q", "T"],
        ["W", "V", "W", "U", "R", "Q", "R", "E", "S", "U", "L", "T", "S"],
        ["I", "N", "S", "L", "Y", "Y", "B", "F", "A", "S", "A", "Z", "H"],
        ["S", "C", "Z", "M", "B", "B", "Y", "H", "T", "L", "O", "F", "A"],
        ["H", "Q", "Y", "A", "N", "S", "D", "Z", "O", "N", "I", "R", "R"],
        ["I", "R", "E", "T", "M", "F", "L", "I", "K", "E", "B", "N", "E"],
        ["N", "S", "S", "E", "D", "Z", "B", "F", "J", "Y", "A", "P", "G"],
        ["G", "H", "X", "R", "Q", "T", "R", "E", "V", "I", "V", "E", "F"],
        ["F", "L", "O", "V", "E", "U", "P", "O", "T", "V", "K", "I", "W"],
        ["X", "B", "T", "K", "M", "U", "N", "E", "V", "N", "Q", "X", "I"],
        ["M", "G", "C", "N", "P", "J", "X", "R", "L", "A", "P", "P", "S"],
      ],
      wordsToFind: [
        "KIND",
        "LOVE",
        "REVIVE",
        "WISHING",
        "SOULMATE",
        "RESULTS",
        "SHARE",
        "LIKE",
        "APPS",
        "HEALING",
      ],
      bg: "/assets/games/wordsQuest/BG 1.png",
    },
    {
      title: " Find The 10 Relationship Terms?",
      fixedBoard: [
        ["F", "Y", "V", "E", "O", "R", "B", "I", "T", "I", "N", "G", "G"],
        ["C", "F", "B", "Y", "R", "Q", "L", "X", "L", "Z", "S", "M", "Q"],
        ["B", "R", "E", "A", "D", "C", "R", "U", "M", "B", "I", "N", "G"],
        ["M", "I", "D", "G", "P", "A", "Q", "L", "E", "D", "T", "Q", "T"],
        ["Z", "E", "W", "A", "R", "T", "F", "O", "G", "X", "U", "T", "R"],
        ["L", "N", "S", "S", "Y", "F", "B", "V", "H", "S", "A", "Z", "E"],
        ["M", "D", "Z", "L", "B", "I", "Y", "E", "O", "F", "T", "F", "D"],
        ["C", "Z", "Y", "I", "N", "S", "D", "B", "S", "N", "I", "R", "F"],
        ["H", "O", "E", "G", "M", "H", "N", "O", "T", "K", "O", "A", "L"],
        ["Q", "N", "S", "H", "D", "I", "B", "M", "I", "Y", "N", "P", "A"],
        ["R", "E", "S", "T", "Q", "N", "T", "B", "N", "T", "S", "Q", "G"],
        ["F", "S", "V", "I", "K", "G", "P", "I", "G", "V", "H", "I", "W"],
        ["X", "B", "T", "N", "M", "B", "E", "N", "C", "H", "I", "N", "G"],
        ["M", "G", "C", "G", "P", "J", "X", "G", "L", "I", "P", "X", "R"],
      ],
      wordsToFind: [
        "ORBITING",
        "BREADCRUMBING",
        "BENCHING",
        "GASLIGHTING",
        "LOVEBOMBING",
        "SITUATIONSHIP",
        "GHOSTING",
        "CATFISHING",
        "FRIENDZONE",
        "REDFLAG",
      ],
      bg: "/assets/games/wordsQuest/BG 2.png",
    },
    {
      title: "Find The 10 Social Media Buzzwords?",
      fixedBoard: [
        ["F", "P", "R", "O", "F", "I", "L", "E", "D", "T", "I", "F", "G"],
        ["C", "Y", "B", "Y", "R", "Q", "L", "X", "L", "Z", "N", "M", "V"],
        ["R", "V", "O", "M", "F", "J", "Q", "K", "J", "U", "F", "R", "I"],
        ["M", "E", "T", "O", "O", "O", "Y", "I", "Z", "D", "L", "Q", "R"],
        ["Q", "D", "W", "R", "R", "E", "L", "F", "B", "P", "U", "T", "A"],
        ["T", "N", "S", "Q", "E", "Y", "B", "L", "J", "S", "E", "Z", "L"],
        ["E", "R", "Z", "L", "B", "N", "Y", "H", "O", "B", "N", "F", "E"],
        ["F", "E", "Y", "B", "N", "S", "D", "Z", "O", "W", "C", "R", "N"],
        ["T", "P", "E", "E", "M", "F", "K", "I", "M", "U", "E", "I", "S"],
        ["C", "O", "S", "Q", "D", "Z", "B", "F", "N", "Y", "R", "R", "T"],
        ["R", "S", "S", "H", "A", "S", "H", "T", "A", "G", "T", "X", "S"],
        ["F", "T", "N", "P", "X", "U", "P", "O", "T", "R", "V", "N", "W"],
        ["X", "B", "T", "A", "L", "G", "O", "R", "I", "T", "H", "M", "I"],
        ["C", "O", "N", "T", "E", "N", "T", "X", "C", "L", "K", "X", "R"],
      ],
      wordsToFind: [
        "PROFILE",
        "METOO",
        "VIRAL",
        "REPOST",
        "HASHTAG",
        "ALGORITHM",
        "CONTENT",
        "INFLUENCER",
        "FOLLOWERS",
        "TRENDING",
      ],
      bg: "/assets/games/wordsQuest/BG 3.png",
    },
    {
      title: "Find The 10 Chat Shortcuts?",
      fixedBoard: [
        ["F", "Y", "V", "E", "E", "D", "L", "R", "T", "H", "N", "F", "V"],
        ["C", "R", "B", "G", "R", "W", "M", "X", "L", "Z", "G", "M", "Y"],
        ["R", "I", "O", "M", "J", "Y", "Q", "K", "J", "U", "T", "R", "I"],
        ["M", "Y", "D", "Z", "D", "Q", "E", "Z", "O", "G", "O", "A", "T"],
        ["Q", "K", "W", "N", "R", "P", "O", "V", "B", "P", "V", "T", "W"],
        ["T", "Y", "S", "Q", "Y", "N", "B", "F", "J", "S", "Z", "D", "L"],
        ["Q", "K", "Z", "L", "B", "F", "Y", "H", "N", "B", "O", "F", "E"],
        ["Y", "C", "Y", "B", "F", "S", "D", "Z", "G", "N", "C", "R", "N"],
        ["F", "R", "E", "E", "O", "F", "I", "M", "L", "D", "T", "I", "S"],
        ["L", "S", "S", "Q", "M", "Z", "B", "F", "J", "Y", "A", "P", "T"],
        ["M", "H", "R", "M", "O", "F", "T", "Q", "R", "U", "T", "X", "F"],
        ["A", "V", "N", "P", "X", "U", "P", "O", "T", "B", "R", "B", "W"],
        ["O", "B", "T", "O", "M", "G", "N", "E", "V", "N", "Q", "X", "I"],
        ["E", "G", "C", "X", "U", "L", "K", "S", "M", "H", "K", "X", "R"],
      ],
      wordsToFind: [
        "IYKYK",
        "GRWM",
        "GOAT",
        "POV",
        "NGL",
        "FOMO",
        "LMAO",
        "OMG",
        "BRB",
        "SMH",
      ],
      bg: "/assets/games/wordsQuest/BG 4.png",
    },
    {
      title: "Find The 10 Puberty Words For Giris?",
      fixedBoard: [
        ["F", "Y", "V", "E", "P", "A", "D", "S", "D", "E", "N", "F", "B"],
        ["C", "P", "B", "Y", "R", "Q", "L", "X", "L", "Z", "G", "M", "R"],
        ["R", "E", "O", "M", "J", "G", "Q", "K", "J", "U", "T", "R", "E"],
        ["M", "R", "D", "Z", "I", "R", "O", "N", "T", "D", "I", "Q", "A"],
        ["M", "I", "W", "N", "R", "O", "Y", "F", "B", "P", "V", "T", "S"],
        ["T", "O", "S", "Q", "Y", "W", "B", "A", "J", "S", "A", "Z", "T"],
        ["Q", "D", "O", "L", "B", "T", "Y", "H", "P", "B", "O", "F", "S"],
        ["F", "S", "Y", "D", "N", "H", "D", "Z", "O", "P", "E", "R", "N"],
        ["B", "R", "E", "E", "S", "F", "M", "S", "Y", "N", "L", "I", "S"],
        ["C", "S", "S", "Q", "D", "W", "B", "F", "D", "A", "T", "E", "S"],
        ["R", "H", "Z", "V", "N", "Z", "I", "Q", "R", "U", "T", "X", "S"],
        ["C", "R", "A", "M", "P", "S", "P", "N", "T", "J", "A", "E", "W"],
        ["X", "B", "T", "K", "M", "U", "N", "E", "G", "N", "Q", "X", "I"],
        ["M", "G", "C", "P", "X", "T", "P", "B", "L", "O", "O", "D", "R"],
      ],
      wordsToFind: [
        "PERIODS",
        "PADS",
        "IRON",
        "GROWTH",
        "APPLES",
        "DATES",
        "CRAMPS",
        "BLOOD",
        "BREASTS",
        "MOODSWING",
      ],
      bg: "/assets/games/wordsQuest/BG 1.png",
    },
    {
      title: "Find The 10 Influencer Words?",
      fixedBoard: [
        ["F", "Y", "V", "E", "E", "C", "O", "L", "L", "A", "B", "F", "J"],
        ["P", "M", "B", "Y", "R", "Q", "L", "X", "L", "Z", "G", "M", "R"],
        ["R", "C", "O", "S", "U", "B", "S", "C", "R", "I", "B", "E", "R"],
        ["O", "M", "D", "Z", "P", "S", "J", "N", "T", "D", "I", "Q", "K"],
        ["M", "T", "W", "N", "R", "O", "Y", "F", "L", "I", "V", "E", "B"],
        ["O", "Q", "S", "G", "Y", "B", "N", "F", "J", "S", "A", "Z", "D"],
        ["T", "C", "V", "L", "I", "A", "Y", "S", "T", "B", "O", "F", "E"],
        ["I", "Z", "L", "B", "N", "V", "D", "Z", "O", "N", "E", "R", "N"],
        ["O", "R", "O", "E", "M", "F", "E", "X", "F", "R", "P", "I", "M"],
        ["N", "S", "G", "Q", "D", "Z", "B", "A", "J", "Y", "S", "P", "E"],
        ["R", "H", "Y", "P", "E", "S", "T", "Q", "W", "U", "T", "X", "R"],
        ["F", "V", "N", "B", "R", "A", "N", "D", "T", "A", "R", "U", "C"],
        ["X", "B", "T", "K", "M", "U", "N", "E", "V", "N", "Y", "X", "H"],
        ["M", "M", "O", "N", "E", "T", "I", "Z", "E", "L", "K", "X", "R"],
      ],
      wordsToFind: [
        "COLLAB",
        "SUBSCRIBE",
        "PROMOTION",
        "LIVE",
        "VLOG",
        "SPONSORS",
        "BRAND",
        "GIVEAWAY",
        "MERCH",
        "MONETIZE",
      ],
      bg: "/assets/games/wordsQuest/BG 2.png",
    },
    {
      title: "Find The 10 social media App Names",
      fixedBoard: [
        ["F", "Y", "V", "P", "I", "N", "T", "E", "R", "E", "S", "T", "N"],
        ["C", "O", "B", "Y", "R", "Q", "L", "D", "L", "Z", "G", "M", "P"],
        ["F", "A", "C", "E", "B", "O", "O", "K", "J", "U", "T", "R", "E"],
        ["M", "O", "D", "Z", "M", "R", "Y", "J", "K", "D", "I", "Q", "F"],
        ["Q", "J", "W", "N", "R", "E", "D", "D", "I", "T", "V", "T", "F"],
        ["T", "B", "S", "Q", "Y", "B", "B", "F", "N", "S", "A", "Z", "D"],
        ["S", "T", "Z", "L", "B", "H", "D", "I", "S", "C", "O", "R", "D"],
        ["J", "N", "Y", "B", "N", "S", "D", "Z", "T", "N", "E", "R", "N"],
        ["V", "R", "A", "E", "M", "X", "Y", "F", "A", "E", "T", "I", "S"],
        ["C", "S", "S", "P", "D", "Z", "B", "F", "G", "Y", "A", "P", "T"],
        ["R", "M", "H", "Q", "C", "U", "T", "H", "R", "E", "A", "D", "S"],
        ["F", "O", "N", "P", "L", "H", "P", "O", "A", "T", "U", "Q", "W"],
        ["V", "J", "T", "K", "M", "U", "A", "E", "M", "N", "Q", "F", "I"],
        ["M", "G", "C", "B", "Y", "O", "U", "T", "U", "B", "E", "K", "R"],
      ],
      wordsToFind: [
        "PINTEREST",
        "FACEBOOK",
        "REDDIT",
        "DISCORD",
        "INSTAGRAM",
        "SNAPCHAT",
        "MOJ",
        "X",
        "THREADS",
        "YOUTUBE",
      ],
      bg: "/assets/games/wordsQuest/BG 3.png",
    },
    {
      title: "Find The 10 Puberty Words For Boys?",
      fixedBoard: [
        ["F", "Y", "V", "E", "V", "O", "I", "C", "E", "E", "N", "F", "V"],
        ["C", "R", "B", "L", "E", "D", "Y", "X", "L", "Z", "G", "M", "W"],
        ["R", "H", "O", "M", "U", "S", "C", "L", "E", "S", "T", "R", "E"],
        ["M", "A", "D", "Z", "D", "Q", "E", "Z", "O", "J", "U", "I", "T"],
        ["Q", "I", "W", "N", "R", "S", "H", "A", "V", "E", "V", "T", "D"],
        ["T", "R", "S", "Q", "Y", "N", "M", "F", "J", "S", "A", "Z", "R"],
        ["Q", "S", "Z", "L", "H", "F", "Y", "E", "H", "B", "O", "F", "E"],
        ["Y", "C", "Y", "B", "E", "S", "D", "Z", "L", "N", "E", "R", "A"],
        ["F", "R", "E", "E", "I", "F", "I", "M", "D", "L", "T", "I", "M"],
        ["S", "S", "S", "Q", "G", "Z", "B", "B", "J", "Y", "A", "P", "S"],
        ["W", "H", "R", "M", "H", "F", "T", "Q", "E", "U", "T", "X", "F"],
        ["E", "V", "N", "P", "T", "U", "P", "O", "T", "A", "Q", "U", "W"],
        ["A", "B", "T", "L", "M", "X", "N", "E", "V", "N", "R", "X", "I"],
        ["T", "G", "C", "X", "A", "C", "N", "E", "K", "X", "K", "D", "R"],
      ],
      wordsToFind: [
        "VOICE",
        "HEIGHT",
        "BEARD",
        "HAIRS",
        "MUSCLES",
        "SWEAT",
        "SMELL",
        "ACNE",
        "SHAVE",
        "WETDREAMS",
      ],
      bg: "/assets/games/wordsQuest/BG 4.png",
    },
    {
      title: "Find The 10 Music Vibe Words?",
      fixedBoard: [
        ["F", "Y", "V", "E", "E", "D", "T", "U", "N", "D", "J", "F", "A"],
        ["C", "M", "C", "Y", "R", "Q", "L", "X", "L", "Z", "G", "M", "Q"],
        ["R", "Z", "H", "B", "J", "P", "Q", "K", "J", "U", "T", "R", "X"],
        ["M", "L", "O", "O", "P", "L", "Y", "R", "I", "C", "S", "Q", "T"],
        ["D", "V", "R", "Z", "R", "A", "L", "B", "I", "D", "Q", "T", "C"],
        ["E", "N", "U", "W", "Y", "Y", "B", "F", "M", "S", "A", "Z", "O"],
        ["S", "C", "S", "B", "B", "L", "Y", "H", "T", "X", "O", "F", "N"],
        ["A", "Q", "Y", "S", "N", "I", "D", "Z", "O", "N", "Y", "R", "C"],
        ["R", "L", "E", "D", "M", "S", "F", "R", "A", "P", "B", "K", "E"],
        ["S", "S", "B", "Z", "R", "T", "B", "F", "J", "Y", "A", "P", "R"],
        ["R", "H", "X", "U", "E", "T", "Q", "O", "T", "V", "L", "F", "T"],
        ["F", "P", "M", "P", "M", "U", "B", "E", "A", "T", "K", "I", "W"],
        ["X", "B", "T", "K", "I", "U", "N", "E", "V", "N", "Q", "X", "I"],
        ["M", "G", "C", "N", "X", "J", "X", "R", "V", "I", "B", "E", "S"],
      ],
      wordsToFind: [
        "REMIX",
        "ALBUM",
        "VIBES",
        "CHORUS",
        "PLAYLIST",
        "RAP",
        "CONCERT",
        "LYRICS",
        "DJ",
        "BEAT",
      ],
      bg: "/assets/games/wordsQuest/BG 1.png",
    },
    {
      title: "Find The 10 Hidden Teen Feelings?",
      fixedBoard: [
        ["F", "E", "B", "Y", "R", "Q", "L", "J", "D", "T", "O", "F", "G"],
        ["C", "Y", "C", "R", "U", "S", "H", "X", "P", "Z", "V", "M", "C"],
        ["R", "V", "O", "M", "L", "J", "Q", "K", "R", "U", "E", "R", "O"],
        ["D", "R", "E", "A", "M", "Z", "Y", "I", "E", "D", "R", "Q", "M"],
        ["Q", "D", "W", "Y", "R", "E", "B", "F", "S", "P", "T", "T", "P"],
        ["J", "N", "S", "Q", "T", "L", "B", "J", "S", "S", "H", "Z", "A"],
        ["E", "E", "Z", "L", "B", "Y", "O", "H", "U", "B", "I", "F", "R"],
        ["F", "Y", "A", "B", "N", "S", "Z", "N", "R", "O", "N", "R", "I"],
        ["T", "F", "E", "L", "M", "F", "K", "I", "E", "U", "K", "I", "S"],
        ["C", "E", "S", "Q", "O", "Z", "B", "F", "N", "L", "N", "Y", "O"],
        ["R", "A", "S", "K", "T", "U", "D", "E", "M", "T", "Y", "X", "N"],
        ["F", "R", "N", "P", "I", "N", "S", "E", "C", "U", "R", "E", "W"],
        ["X", "B", "T", "C", "X", "U", "P", "O", "T", "R", "V", "N", "I"],
        ["L", "X", "C", "O", "N", "F", "U", "S", "I", "O", "N", "X", "R"],
      ],
      wordsToFind: [
        "INSECURE",
        "PRESSURE",
        "JEALOUS",
        "CRUSH",
        "LONELY",
        "CONFUSION",
        "OVERTHINK",
        "FEAR",
        "DREAM",
        "COMPARISON",
      ],
      bg: "/assets/games/wordsQuest/BG 2.png",
    },
  ],
  hard: [],
};
