export const GAME_DATA = {
  easy: [
    {
      word: "AMET",
      validWords: ["TEAM", "TEA", "EAT", "MAT", "ME", "AM", "AT"],
    },
    {
      word: "RTAS",
      validWords: ["STAR", "RAT", "TAR", "SAT", "ART", "AT", "AS"],
    },
    {
      word: "DORW",
      validWords: ["WORD", "ROW", "ROD", "DOW", "DO", "OR"],
    },
    {
      word: "YLAP",
      validWords: ["PLAY", "PAL", "LAY", "PAY", "YAP", "LAP"],
    },
    {
      word: "NIAR",
      validWords: ["RAIN", "RAN", "AIR", "IN", "AN"],
    },
    {
      word: "HSIF",
      validWords: ["FISH", "HIS", "IF", "IS"],
    },
    {
      word: "ADHN",
      validWords: ["HAND", "HAD", "AND", "AN", "AD"],
    },
    {
      word: "WONS",
      validWords: ["SNOW", "NOW", "SON", "NO", "ON", "WON"],
    },
    {
      word: "GRFO",
      validWords: ["FROG", "FOR", "GO", "OR"],
    },
    {
      word: "NOIL",
      validWords: ["LION", "OIL", "IN", "ON"],
    },
    {
      word: "TEIK",
      validWords: ["KITE", "KIT", "TIE", "IT"],
    },
    {
      word: "PHIS",
      validWords: ["SHIP", "HIP", "HIS", "IS"],
    },
  ],
  medium: [
    {
      word: "CTAER",
      validWords: [
        "REACT",
        "RATE",
        "CARE",
        "RACE",
        "CART",
        "TEAR",
        "TEA",
        "EAT",
        "CAT",
        "CAR",
        "RAT",
        "AT",
      ],
    },
    {
      word: "CRANE",
      validWords: [
        "RACE",
        "CARE",
        "ACRE",
        "CANE",
        "ARC",
        "CAR",
        "EAR",
        "ARE",
        "ACE",
        "NEAR",
      ],
    },
    {
      word: "TENSO",
      validWords: [
        "STONE",
        "TONE",
        "ONES",
        "NOSE",
        "NOTE",
        "SET",
        "NET",
        "SON",
        "ONE",
        "TEN",
      ],
    },
    {
      word: "TRAEH",
      validWords: [
        "HEART",
        "RATE",
        "TEAR",
        "HARE",
        "HEAR",
        "ART",
        "EAR",
        "HAT",
        "EAT",
        "HER",
      ],
    },
    {
      word: "LNPAT",
      validWords: [
        "PLANT",
        "PANT",
        "PLAN",
        "PLAT",
        "ANT",
        "PAN",
        "TAP",
        "PAT",
        "LAP",
      ],
    },
    {
      word: "REOSH",
      validWords: [
        "SHORE",
        "HORSE",
        "HOSE",
        "SHOE",
        "SORE",
        "ROSE",
        "HER",
        "SHE",
        "ORE",
      ],
    },
    {
      word: "DREBA",
      validWords: [
        "BREAD",
        "BEAD",
        "BARE",
        "BEAR",
        "READ",
        "DARE",
        "DEAR",
        "BAD",
        "BED",
        "RED",
        "EAR",
      ],
    },
    {
      word: "RFALE",
      validWords: [
        "FLARE",
        "FEAL",
        "LEAF",
        "FARE",
        "FEAR",
        "REAL",
        "EARL",
        "ELF",
        "ARE",
        "EAR",
        "ERA",
      ],
    },
    {
      word: "PAERG",
      validWords: [
        "GRAPE",
        "PAGE",
        "REAP",
        "GEAR",
        "PEAR",
        "PARE",
        "APE",
        "AGE",
        "GAP",
        "PEG",
        "EAR",
      ],
    },
    {
      word: "SHTOG",
      validWords: [
        "GHOST",
        "SHOT",
        "HOGS",
        "GOSH",
        "HOST",
        "GOT",
        "HOG",
        "HOT",
        "SOT",
      ],
    },
  ],
  hard: [
    {
      word: "NHCITEK",
      validWords: [
        "THICK",
        "THINK",
        "KITE",
        "TICK",
        "TINE",
        "ETHNIC",
        "THINE",
        "NICHE",
        "INCH",
        "ETCH",
        "KITH",
        "KNIT",
        "THE",
        "TEN",
        "NET",
      ],
    },
    {
      word: "LECCTOLABLES",
      validWords: [
        "COLLECTABLES",
        "COLLECTABLE",
        "COLLECTS",
        "STABLE",
        "CALLED",
        "COLLECT",
        "BATTLE",
        "SELECT",
        "BELSACE",
        "STACLE",
        "TABLES",
        "LOCATE",
        "COAST",
        "CELLO",
        "STALE",
        "LABEL",
        "CABLE",
        "LOCAL",
        "CELL",
        "BELL",
        "CALL",
        "BASE",
        "LOST",
        "SALT",
        "ABLE",
        "COAL",
      ],
    },
    {
      word: "NGNIDNATSURED",
      validWords: [
        "UNDERSTANDING",
        "STANDARDIZED",
        "RESOUNDING",
        "DRAINING",
        "READING",
        "GRINDING",
        "SUNDERING",
        "DURING",
        "DINNER",
        "SANDER",
        "UNDER",
        "GRAIN",
        "SOUND",
        "GUARD",
        "STAND",
        "ROUND",
        "DRAG",
        "SING",
        "RING",
        "SUNG",
        "RAIN",
        "SAND",
        "DRUG",
        "GUNS",
        "DUNG",
        "SURE",
      ],
    },
    {
      word: "HPNOITALRESI",
      validWords: [
        "RELATIONSHIP",
        "RELATION",
        "SHIPMENT",
        "PAINTERS",
        "RETIAN",
        "SPANIEL",
        "HAIRPIN",
        "PRISON",
        "PLANET",
        "SILENT",
        "PISTOL",
        "RETAIN",
        "STERN",
        "SHIRT",
        "TRAIN",
        "PLAIN",
        "PAINT",
        "PANEL",
        "SHALE",
        "POINT",
        "SHIP",
        "RAIL",
        "TRIP",
        "LENT",
        "PLANT",
        "STAR",
        "THEN",
        "LINE",
        "REAL",
      ],
    },
    {
      word: "VETINESREMTDA",
      validWords: [
        "ADVERTISEMENTS",
        "ADVERTISEMENT",
        "ADVERTISE",
        "INVESTMENT",
        "DETERMINES",
        "RESENTMENT",
        "ADVERTISER",
        "STEAMER",
        "READMIT",
        "RETIRED",
        "DREAMS",
        "STREAM",
        "MASTER",
        "STARE",
        "TRADE",
        "SMART",
        "EVENT",
        "NEVER",
        "REEST",
        "SENT",
        "DEER",
        "MERE",
        "TEAM",
        "STAR",
        "SAVE",
      ],
    },
    {
      word: "CCNOTIURSREON",
      validWords: [
        "RECONSTRUCTION",
        "CONSTRUCTION",
        "CONSTRUCTOR",
        "INSTRUCTION",
        "CONTINUES",
        "RECOUNT",
        "SECTION",
        "NOTICE",
        "COUSIN",
        "COURTS",
        "TENOR",
        "UNITE",
        "STORE",
        "COUNT",
        "OUTER",
        "NOISE",
        "COIN",
        "UNIT",
        "IRON",
        "CORE",
        "NOTE",
        "REST",
        "SENT",
        "ONCE",
        "TOUR",
      ],
    },
    {
      word: "TNEMTRAPMOCS",
      validWords: [
        "COMPARTMENTS",
        "COMPARTMENT",
        "COMPONENT",
        "COMPARE",
        "PARTNER",
        "PARENT",
        "RECOUP",
        "MENTOR",
        "TAMPER",
        "PERSON",
        "REMAP",
        "MOUNT",
        "STOMP",
        "TRACE",
        "SMART",
        "DORM",
        "POST",
        "TEAM",
        "PART",
        "NEAR",
        "COME",
        "MEAT",
        "ROPE",
        "SOME",
        "SENT",
      ],
    },
  ],
};
