import { Cell, Clue } from "@/types";

export const GRID: Cell[][] = [
  [
    { answer: "C", number: 1 },
    { answer: "A" },
    { answer: "T" },
    { answer: null, isBlocked: true },
    { answer: "S", number: 2 },
    { answer: "U" },
    { answer: "N" },
    { answer: null, isBlocked: true },
    { answer: "B", number: 3 },
    { answer: "A" },
    { answer: "L" },
    { answer: "L" },
    { answer: null, isBlocked: true },
    { answer: "F", number: 4 },
    { answer: "O" },
  ],
  [
    { answer: "O" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "T" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "O" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: "R", number: 5 },
    { answer: "U" },
    { answer: "N" },
    { answer: null, isBlocked: true },
    { answer: "A" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "O" },
    { answer: null, isBlocked: true },
    { answer: "P", number: 6 },
    { answer: "O" },
    { answer: "L" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: "N" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "R" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "K" },
    { answer: null, isBlocked: true },
    { answer: "O" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: "D", number: 7 },
    { answer: "O" },
    { answer: "G" },
    { answer: null, isBlocked: true },
    { answer: "F", number: 8 },
    { answer: "I" },
    { answer: "R", number: 12 },
    { answer: "E" },
    { answer: null, isBlocked: true },
    { answer: "L" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: "N" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "U" },
    { answer: null, isBlocked: true },
    { answer: "A" },
    { answer: null, isBlocked: true },
    { answer: "M", number: 9 },
    { answer: "O" },
    { answer: "O" },
    { answer: "N" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: "H", number: 10 },
    { answer: "A" },
    { answer: "N" },
    { answer: "D" },
    { answer: null, isBlocked: true },
    { answer: "R" },
    { answer: null, isBlocked: true },
    { answer: "T" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "W", number: 11 },
    { answer: "E" },
  ],
];

export const CLUES: Clue[] = [
  // Across
  {
    number: 1,
    clue: "Feline pet",
    answer: "CAT",
    startRow: 0,
    startCol: 0,
    direction: "across",
  },
  {
    number: 2,
    clue: "Bright star in our solar system",
    answer: "SUN",
    startRow: 0,
    startCol: 4,
    direction: "across",
  },
  {
    number: 3,
    clue: "Round object used in sports",
    answer: "BALL",
    startRow: 0,
    startCol: 8,
    direction: "across",
  },
  {
    number: 4,
    clue: "Two letters",
    answer: "FO",
    startRow: 0,
    startCol: 13,
    direction: "across",
  },
  {
    number: 5,
    clue: "Move quickly on foot",
    answer: "RUN",
    startRow: 2,
    startCol: 0,
    direction: "across",
  },
  {
    number: 6,
    clue: "Farm animal that oinks",
    answer: "PIG",
    startRow: 2,
    startCol: 10,
    direction: "across",
  },
  {
    number: 7,
    clue: "Man's best friend",
    answer: "DOG",
    startRow: 4,
    startCol: 1,
    direction: "across",
  },
  {
    number: 8,
    clue: "Destructive blaze",
    answer: "FIRE",
    startRow: 4,
    startCol: 5,
    direction: "across",
  },
  {
    number: 9,
    clue: "Earth's satellite",
    answer: "MOON",
    startRow: 5,
    startCol: 9,
    direction: "across",
  },
  {
    number: 10,
    clue: "Body part with fingers",
    answer: "HAND",
    startRow: 6,
    startCol: 0,
    direction: "across",
  },
  {
    number: 11,
    clue: "You and I",
    answer: "WE",
    startRow: 6,
    startCol: 13,
    direction: "across",
  },

  // Down
  {
    number: 1,
    clue: "Maize vegetable",
    answer: "CORN",
    startRow: 0,
    startCol: 0,
    direction: "down",
  },
  {
    number: 2,
    clue: "Celestial body with twinkle",
    answer: "STAR",
    startRow: 0,
    startCol: 4,
    direction: "down",
  },
  {
    number: 3,
    clue: "Large tome or novel",
    answer: "BOOK",
    startRow: 0,
    startCol: 8,
    direction: "down",
  },
  {
    number: 6,
    clue: "Sport played on horseback",
    answer: "POLO",
    startRow: 2,
    startCol: 10,
    direction: "down",
  },
  {
    number: 7,
    clue: "Genetic material passed from parents",
    answer: "DNA",
    startRow: 4,
    startCol: 1,
    direction: "down",
  },
  {
    number: 8,
    clue: "Furry pet sound",
    answer: "FUR",
    startRow: 4,
    startCol: 5,
    direction: "down",
  },
  {
    number: 12,
    clue: "Large rodent",
    answer: "RAT",
    startRow: 4,
    startCol: 7,
    direction: "down",
  },
];
