export const PUZZLE_DIFFICULTY = {
  easy: {
    img: "/assets/puzzle/easy/bg.png",
    socialMedia: {
      title: "Click & Connect",
      description: "Explore simple social media words and features.",
      data: ["CHAT", "LIKE", "TAG", "APP", "POST", "BIO", "DM", "VIEW"],
    },
    career: {
      title: "Career Starters",
      description: "Begin with everyday job roles around you.",
      data: [
        "CHEF",
        "GUARD",
        "CLERK",
        "NURSE",
        "DRIVER",
        "WAITER",
        "JANITOR",
        "ACTOR",
      ],
    },
    icons: {
      title: "Icon Hunt",
      description: "Find common digital icons used in daily apps.",
      data: ["HOME", "MAIL", "SAVE", "CALL", "LOCK", "EXIT", "HELP", "CHAT"],
    },
    difficulty: "Easy",
  },

  medium: {
    img: "/assets/puzzle/medium/bg.png",
    socialMedia: {
      title: "Social Surf",
      description: "Spot trending platforms and medium-level terms.",
      data: [
        "COMMENT",
        "SNAP",
        "REPOST",
        "PROFILE",
        "FOLLOW",
        "TRENDS",
        "STATUS",
        "REACT",
      ],
    },
    career: {
      title: "Work & Wisdom",
      description: "Discover mid-level career paths across industries.",
      data: [
        "TEACHER",
        "DENTIST",
        "WRITER",
        "BANKER",
        "MECHANIC",
        "ENGINEER",
        "FIREMAN",
        "DESIGNER",
      ],
    },
    icons: {
      title: "UI Explorer",
      description: "Search for recognizable interface elements.",
      data: [
        "UPLOAD",
        "CAMERA",
        "NOTIFY",
        "REFRESH",
        "SEARCH",
        "FILTER",
        "RECORD",
        "DELETE",
      ],
    },
    difficulty: "Medium",
  },

  hard: {
    img: "/assets/puzzle/hard/bg.png",
    socialMedia: {
      title: "Digital Matrix",
      description: "Tackle deep, viral, and tech-heavy social words.",
      data: [
        "INFLUENCER",
        "ALGORITHM",
        "ENGAGEMENT",
        "SCHEDULING",
        "MONETIZED",
        "SUBSCRIBERS",
        "DISCOVERED",
        "COMMENTING",
      ],
    },
    career: {
      title: "Elite Professions",
      description: "Crack top-tier and technical job titles.",
      data: [
        "PHARMACIST",
        "DATAENGINEER",
        "NEUROLOGIST",
        "CYBERLAWYER",
        "ANALYST",
        "ARCHITECT",
        "SCIENTIST",
        "STRATEGIST",
      ],
    },
    icons: {
      title: "Symbol Search",
      description: "Decode UI/UX design and feature icons.",
      data: [
        "DASHBOARD",
        "CALENDAR",
        "TOOLBAR",
        "MULTITASK",
        "SIDEPANEL",
        "SETTINGS",
        "WIDGETS",
        "NAVIGATOR",
      ],
    },
    difficulty: "Hard",
  },
};
