import { QuizData } from "@/pages/quiz";

export const QUIZ_ITEMS = [
  {
    id: "11011",
    label: "Games",
    value: "games",
    bgColor: "bg-gradient-to-br from-red-500 to-red-700",
    shadowColor: "rgba(239, 68, 68, 0.4)",
    glowColor: "rgba(239, 68, 68, 0.6)",
    imgSrc: "/assets/assesments/quiz/socialMedia/bg.png",
    imgAlt: "Games Background",
    icon: "🎮",
    description: "Test your knowledge of gaming history, consoles, and culture",
    category: "Entertainment",
  },
  {
    id: "11012",
    label: "Social Media",
    value: "socialMedia",
    bgColor: "bg-gradient-to-br from-green-500 to-green-700",
    shadowColor: "rgba(34, 197, 94, 0.4)",
    glowColor: "rgba(34, 197, 94, 0.6)",
    imgSrc: "/assets/assesments/quiz/socialMedia/bg.png",
    imgAlt: "Social Media Background",
    icon: "📱",
    description:
      "Challenge your understanding of social media platforms and trends",
    category: "Digital Wellness",
  },
  {
    id: "11013",
    label: "Mobile",
    value: "mobile",
    bgColor: "bg-gradient-to-br from-yellow-400 to-yellow-600",
    shadowColor: "rgba(245, 158, 11, 0.4)",
    glowColor: "rgba(245, 158, 11, 0.6)",
    imgSrc: "/assets/assesments/quiz/socialMedia/bg.png",
    imgAlt: "Mobile Background",
    icon: "📲",
    description: "Quiz yourself on mobile technology and its evolution",
    category: "Digital Health",
  },
  {
    id: "11014",
    label: "Gambling",
    value: "gambling",
    bgColor: "bg-gradient-to-br from-blue-500 to-blue-700",
    shadowColor: "rgba(59, 130, 246, 0.4)",
    glowColor: "rgba(59, 130, 246, 0.6)",
    imgSrc: "/assets/assesments/quiz/socialMedia/bg.png",
    imgAlt: "Gambling Background",
    icon: "🎰",
    description: "Test your knowledge of gambling history, and types",
    category: "Risk Assessment",
  },
];

export const QUIZ_DATA: Record<string, QuizData> = {
  games: {
    id: "games",
    title: "Gaming Knowledge Quiz",
    subtitle: "Test Your Gaming IQ",
    description:
      "Trivia questions about gaming history, consoles, and culture.",
    icon: "🎮",
    bgColor: "bg-red-500",
    accentColor: "text-red-600",
    gradientFrom: "from-red-500",
    gradientTo: "to-red-700",
    questions: [
      {
        id: 1,
        question: "Which company developed the first keypad mobile phone?",
        options: ["Motorola", "Apple", "Nokia", "Samsung"],
        type: "multiple",
        correctAnswer: "Motorola",
      },
      {
        id: 2,
        question: "Which is the highest-selling video game of all time?",
        options: ["Minecraft", "GTA V", "Tetris", "PUBG"],
        type: "multiple",
        correctAnswer: "Minecraft",
      },
      {
        id: 3,
        question: "What year was the PlayStation 2 released?",
        options: ["2000", "2001", "1999", "1998"],
        type: "multiple",
        correctAnswer: "2000",
      },
      {
        id: 4,
        question: "What does 'FPS' stand for in gaming?",
        options: [
          "First Player Shooter",
          "Fast Player Shooter",
          "First Person Shooter",
          "Frame Per Second",
        ],
        type: "multiple",
        correctAnswer: "First Person Shooter",
      },
      {
        id: 5,
        question: "Who owns the Halo game franchise?",
        options: ["Sony", "Nintendo", "Microsoft", "Activision"],
        type: "multiple",
        correctAnswer: "Microsoft",
      },
    ],
    resultCategories: ["Novice", "Intermediate", "Advanced", "Pro Gamer"],
  },
  socialMedia: {
    id: "socialMedia",
    title: "Social Media Knowledge Quiz",
    subtitle: "Test Your Social Media Savvy",
    description: "Check how well you know the platforms you scroll daily.",
    icon: "📱",
    bgColor: "bg-green-500",
    accentColor: "text-green-600",
    gradientFrom: "from-green-500",
    gradientTo: "to-green-700",
    questions: [
      {
        id: 1,
        question: "Which company owns Instagram?",
        options: ["Google", "Twitter", "Meta", "Snapchat"],
        type: "multiple",
        correctAnswer: "Meta",
      },
      {
        id: 2,
        question:
          "Which was one of the first social media platforms launched as a mobile app?",
        options: ["Snapchat", "Instagram", "Twitter", "Facebook"],
        type: "multiple",
        correctAnswer: "Instagram",
      },
      {
        id: 3,
        question: "Which app popularized short-form vertical videos?",
        options: ["Snapchat", "TikTok", "YouTube", "Instagram"],
        type: "multiple",
        correctAnswer: "TikTok",
      },
      {
        id: 4,
        question: "LinkedIn is primarily used for?",
        options: ["Job networking", "Gaming", "Shopping", "Messaging"],
        type: "multiple",
        correctAnswer: "Job networking",
      },
      {
        id: 5,
        question: "Which platform introduced 'Stories' first?",
        options: ["Instagram", "Facebook", "Snapchat", "WhatsApp"],
        type: "multiple",
        correctAnswer: "Snapchat",
      },
      {
        id: 6,
        question: "What does 'DM' stand for on social media?",
        options: [
          "Direct Message",
          "Download Media",
          "Data Metric",
          "Delete Mode",
        ],
        type: "multiple",
        correctAnswer: "Direct Message",
      },
      {
        id: 7,
        question: "Which social platform uses the term 'Reels'?",
        options: ["TikTok", "Facebook", "Instagram", "YouTube"],
        type: "multiple",
        correctAnswer: "Instagram",
      },
      {
        id: 8,
        question: "What is YouTube’s premium subscription called?",
        options: ["YouTube Plus", "YouTube Premium", "YT Pro", "YouTube Elite"],
        type: "multiple",
        correctAnswer: "YouTube Premium",
      },
      {
        id: 9,
        question: "Which company owns WhatsApp?",
        options: ["Google", "Telegram", "Meta", "Apple"],
        type: "multiple",
        correctAnswer: "Meta",
      },
      {
        id: 10,
        question:
          "Which social media platform was the first to focus on job applications and professional networking?",
        options: ["LinkedIn", "Facebook", "Twitter", "Google+"],
        type: "multiple",
        correctAnswer: "LinkedIn",
      },
      {
        id: 11,
        question: "Which social platform was formerly known as Musical.ly?",
        options: ["TikTok", "Instagram", "Vine", "Facebook"],
        type: "multiple",
        correctAnswer: "TikTok",
      },
      {
        id: 12,
        question: "What color is Twitter's logo?",
        options: ["Red", "Green", "Blue", "Black"],
        type: "multiple",
        correctAnswer: "Blue",
      },
      {
        id: 13,
        question: "Who founded Facebook?",
        options: ["Jeff Bezos", "Mark Zuckerberg", "Bill Gates", "Elon Musk"],
        type: "multiple",
        correctAnswer: "Mark Zuckerberg",
      },
      {
        id: 14,
        question: "Which social app is known for disappearing messages?",
        options: ["WhatsApp", "Instagram", "Snapchat", "Messenger"],
        type: "multiple",
        correctAnswer: "Snapchat",
      },
      {
        id: 15,
        question: "Which feature allows Instagram users to go live?",
        options: ["IGTV", "Live Broadcast", "Live Stories", "Instagram Live"],
        type: "multiple",
        correctAnswer: "Instagram Live",
      },
      {
        id: 16,
        question:
          "Which social media platform was the first to support native emoji reactions on posts?",
        options: ["Facebook", "Twitter", "Instagram", "Snapchat"],
        type: "multiple",
        correctAnswer: "Facebook",
      },
      {
        id: 17,
        question: "Which platform uses 'Pins' to save ideas?",
        options: ["Reddit", "Facebook", "Pinterest", "Tumblr"],
        type: "multiple",
        correctAnswer: "Pinterest",
      },
      {
        id: 18,
        question: "What does ‘viral’ mean on social media?",
        options: ["Deleted", "Copied", "Becomes popular quickly", "Private"],
        type: "multiple",
        correctAnswer: "Becomes popular quickly",
      },
      {
        id: 19,
        question: "Who acquired Twitter in 2022?",
        options: ["Jeff Bezos", "Elon Musk", "Mark Cuban", "Bill Gates"],
        type: "multiple",
        correctAnswer: "Elon Musk",
      },
      {
        id: 20,
        question: "What’s the minimum age to create a Facebook account?",
        options: ["13", "16", "18", "15"],
        type: "multiple",
        correctAnswer: "13",
      },
      {
        id: 21,
        question: "Which platform is best known for short anonymous Q&A?",
        options: ["Facebook", "ASKfm", "Reddit", "Quora"],
        type: "multiple",
        correctAnswer: "ASKfm",
      },
      {
        id: 22,
        question: "Which feature is NOT available on Twitter?",
        options: ["Fleets", "Spaces", "Reels", "Lists"],
        type: "multiple",
        correctAnswer: "Reels",
      },
      {
        id: 23,
        question: "What does 'IG' stand for?",
        options: [
          "Instant Gallery",
          "Instagram",
          "Image Grid",
          "Internet Guide",
        ],
        type: "multiple",
        correctAnswer: "Instagram",
      },
      {
        id: 24,
        question: "Which app introduced the concept of 'Followers' first?",
        options: ["Twitter", "Facebook", "YouTube", "Instagram"],
        type: "multiple",
        correctAnswer: "Twitter",
      },
      {
        id: 25,
        question: "Which term refers to fake social media accounts?",
        options: ["Spam", "Bots", "Ghosts", "Zombies"],
        type: "multiple",
        correctAnswer: "Bots",
      },
    ],
    resultCategories: ["Beginner", "Casual User", "Influencer", "Social Guru"],
  },
  mobile: {
    id: "mobile",
    title: "Mobile Technology Quiz",
    subtitle: "How Much Do You Know About Phones?",
    description: "Trivia questions on mobile evolution, hardware, and tech.",
    icon: "📲",
    bgColor: "bg-yellow-500",
    accentColor: "text-yellow-600",
    gradientFrom: "from-yellow-400",
    gradientTo: "to-yellow-600",
    questions: [
      {
        id: 1,
        question: "Which phone is considered the first smartphone?",
        options: ["iPhone", "Nokia 3310", "IBM Simon", "Motorola Razr"],
        type: "multiple",
        correctAnswer: "IBM Simon",
      },
      {
        id: 2,
        question: "When was the first iPhone released?",
        options: ["2005", "2006", "2007", "2008"],
        type: "multiple",
        correctAnswer: "2007",
      },
      {
        id: 3,
        question: "Which mobile OS is open-source?",
        options: ["iOS", "Windows Phone", "Android", "Blackberry OS"],
        type: "multiple",
        correctAnswer: "Android",
      },
      {
        id: 4,
        question: "Which brand launched the first 108MP smartphone camera?",
        options: ["Apple", "Xiaomi", "Samsung", "OnePlus"],
        type: "multiple",
        correctAnswer: "Samsung",
      },
      {
        id: 5,
        question: "What does 5G stand for?",
        options: ["5th Generation", "5 Gigabytes", "5Ghz Band", "Fast Network"],
        type: "multiple",
        correctAnswer: "5th Generation",
      },
    ],
    resultCategories: ["Basic User", "Tech Curious", "Techie", "Phone Whiz"],
  },
  gambling: {
    id: "gambling",
    title: "Gambling Knowledge Quiz",
    subtitle: "Know the World of Gambling",
    description: "Test your knowledge of gambling rules, history, and types.",
    icon: "🎰",
    bgColor: "bg-blue-500",
    accentColor: "text-blue-600",
    gradientFrom: "from-blue-500",
    gradientTo: "to-blue-700",
    questions: [
      {
        id: 1,
        question:
          "Which country is known as the gambling capital of the world?",
        options: ["Monaco", "Macau", "Las Vegas", "Singapore"],
        type: "multiple",
        correctAnswer: "Macau",
      },
      {
        id: 2,
        question: "What is the term for a card count of 21 in Blackjack?",
        options: ["Perfect", "Bust", "Hit", "Blackjack"],
        type: "multiple",
        correctAnswer: "Blackjack",
      },
      {
        id: 3,
        question: "What color is zero in a roulette wheel?",
        options: ["Red", "Black", "Green", "Blue"],
        type: "multiple",
        correctAnswer: "Green",
      },
      {
        id: 4,
        question: "In Poker, which hand is strongest?",
        options: [
          "Full House",
          "Straight Flush",
          "Four of a Kind",
          "Royal Flush",
        ],
        type: "multiple",
        correctAnswer: "Royal Flush",
      },
      {
        id: 5,
        question: "Which lottery offers the biggest jackpots in the U.S.?",
        options: [
          "Mega Millions",
          "Powerball",
          "Lucky for Life",
          "EuroMillions",
        ],
        type: "multiple",
        correctAnswer: "Powerball",
      },
    ],
    resultCategories: [
      "Beginner",
      "Risk Taker",
      "Strategist",
      "Gambling Expert",
    ],
  },
};

export const ICON_SETS = {
  mobile: [
    "📱",
    "📞",
    "💻",
    "⌚",
    "🎧",
    "🔋",
    "📡",
    "💾",
    "🖥️",
    "📺",
    "🎮",
    "📷",
  ],
  games: [
    "🎮",
    "🕹️",
    "🎯",
    "🎲",
    "🃏",
    "🎪",
    "🎨",
    "🎭",
    "🎬",
    "🎵",
    "🎸",
    "🎹",
  ],
  gambling: [
    "🎰",
    "🎲",
    "🃏",
    "♠️",
    "♥️",
    "♦️",
    "♣️",
    "🎯",
    "🏆",
    "💰",
    "💎",
    "🎊",
  ],
  socialMedia: [
    "📱",
    "💬",
    "📷",
    "📹",
    "👥",
    "❤️",
    "👍",
    "📢",
    "🔔",
    "📧",
    "💌",
    "🌐",
  ],
};
