import { Cell, Clue } from "@/types";

export const GRID_SOCIAL_EASY: Cell[][] = [
  [
    { answer: "A", number: 1 },
    { answer: "D" },
    { answer: "S" },
    { answer: null, isBlocked: true },
    { answer: "T", number: 2 },
    { answer: "A" },
    { answer: "G" },
    { answer: null, isBlocked: true },
    { answer: "L", number: 3 },
    { answer: "I" },
    { answer: "K" },
    { answer: "E" },
    { answer: null, isBlocked: true },
    { answer: "A", number: 4 },
    { answer: "I" },
  ],
  [
    { answer: "P" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "R" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "I" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: "P", number: 5 },
    { answer: "I" },
    { answer: "N" },
    { answer: null, isBlocked: true },
    { answer: "I" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "M" },
    { answer: null, isBlocked: true },
    { answer: "R", number: 6 },
    { answer: "C" },
    { answer: "V" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: "S" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "M" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "I" },
    { answer: null, isBlocked: true },
    { answer: "I" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: "V", number: 7 },
    { answer: "I" },
    { answer: "D" },
    { answer: null, isBlocked: true },
    { answer: "C", number: 8 },
    { answer: "H" },
    { answer: "A", number: 12 },
    { answer: "T" },
    { answer: null, isBlocked: true },
    { answer: "S" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: "C" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "A" },
    { answer: null, isBlocked: true },
    { answer: "D" },
    { answer: null, isBlocked: true },
    { answer: "G", number: 9 },
    { answer: "O" },
    { answer: "A" },
    { answer: "L" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: "A", number: 10 },
    { answer: "R" },
    { answer: "T" },
    { answer: "S" },
    { answer: null, isBlocked: true },
    { answer: "M" },
    { answer: null, isBlocked: true },
    { answer: "D" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "D", number: 11 },
    { answer: "M" },
  ],
];

export const CLUES_SOCIAL_EASY: Clue[] = [
  // Across
  {
    number: 1,
    clue: "Promotional content you often see on social media feeds",
    answer: "ADS",
    startRow: 0,
    startCol: 0,
    direction: "across",
  },
  {
    number: 2,
    clue: "Social label with #",
    answer: "TAG",
    startRow: 0,
    startCol: 4,
    direction: "across",
  },
  {
    number: 3,
    clue: "Facebook thumbs-up",
    answer: "LIKE",
    startRow: 0,
    startCol: 8,
    direction: "across",
  },
  {
    number: 4,
    clue: "Instagram ___ filter",
    answer: "AI",
    startRow: 0,
    startCol: 13,
    direction: "across",
  },
  {
    number: 5,
    clue: "Save a post on Pinterest or mark a chat in messaging apps",
    answer: "PIN",
    startRow: 2,
    startCol: 0,
    direction: "across",
  },
  {
    number: 6,
    clue: "Short for 'receive' in messages",
    answer: "RCV",
    startRow: 2,
    startCol: 10,
    direction: "across",
  },
  {
    number: 7,
    clue: "Short clip on TikTok",
    answer: "VID",
    startRow: 4,
    startCol: 1,
    direction: "across",
  },
  {
    number: 8,
    clue: "Text conversation online",
    answer: "CHAT",
    startRow: 4,
    startCol: 5,
    direction: "across",
  },
  {
    number: 9,
    clue: "A follower’s end ambition",
    answer: "GOAL",
    startRow: 5,
    startCol: 9,
    direction: "across",
  },
  {
    number: 10,
    clue: "Creative category on Instagram or Pinterest",
    answer: "ARTS",
    startRow: 6,
    startCol: 0,
    direction: "across",
  },
  {
    number: 11,
    clue: "Private inbox message",
    answer: "DM",
    startRow: 6,
    startCol: 13,
    direction: "across",
  },

  // Down
  {
    number: 1,
    clue: "Software programs you download for social media or messaging",
    answer: "APPS",
    startRow: 0,
    startCol: 0,
    direction: "down",
  },
  {
    number: 2,
    clue: "Cut part of a video or reel",
    answer: "TRIM",
    startRow: 0,
    startCol: 4,
    direction: "down",
  },
  {
    number: 3,
    clue: "Story duration or caption length cap",
    answer: "LIMIT",
    startRow: 0,
    startCol: 8,
    direction: "down",
  },
  {
    number: 6,
    clue: "Art print style popular on Instagram",
    answer: "RISO",
    startRow: 2,
    startCol: 10,
    direction: "down",
  },
  {
    number: 7,
    clue: "Retro video player, now meme-worthy",
    answer: "VCR",
    startRow: 4,
    startCol: 1,
    direction: "down",
  },
  {
    number: 8,
    clue: "Short for camera on Snapchat",
    answer: "CAM",
    startRow: 4,
    startCol: 5,
    direction: "down",
  },
  {
    number: 12,
    clue: "Tap to follow or friend someone",
    answer: "ADD",
    startRow: 4,
    startCol: 7,
    direction: "down",
  },
];
