import { Cell, Clue } from "@/types";

export const GRID_SOCIAL_HARD: Cell[][] = [
  [
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "N", number: 1 },
    { answer: "O" },
    { answer: "T" },
    { answer: "I", number: 2 },
    { answer: "F" },
    { answer: "I", number: 3 },
    { answer: "C" },
    { answer: "A" },
    { answer: "T" },
    { answer: "I" },
    { answer: "O" },
    { answer: "N" },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "S" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "G" },
    { answer: null, isBlocked: true },
    { answer: "N" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: "R", number: 4 },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "F" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "T" },
    { answer: null, isBlocked: true },
    { answer: "F", number: 5 },
    { answer: "Y" },
    { answer: "P" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: "E" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "W" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "V" },
    { answer: null, isBlocked: true },
    { answer: "L" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: "P" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "U" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: "L" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "I", number: 6 },
    { answer: "M", number: 7 },
    { answer: "P" },
    { answer: "R" },
    { answer: "E" },
    { answer: "S" },
    { answer: "S" },
    { answer: "I" },
    { answer: "O" },
    { answer: "N" },
    { answer: "S" },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: "Y" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "E" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "N" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: "A", number: 8 },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "T" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "C", number: 9 },
    { answer: "O" },
    { answer: "L" },
    { answer: "L" },
    { answer: "A" },
    { answer: "B" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: "N" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "A" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "E" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "G", number: 10 },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: "A" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "V" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "R", number: 11 },
    { answer: "A" },
    { answer: "G" },
    { answer: "E" },
    { answer: "B" },
    { answer: "A" },
    { answer: "I" },
    { answer: "T" },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: "L" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "E" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "F" },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: "Y" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "R" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "F", number: 12 },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: "T" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "S" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "T", number: 13 },
    { answer: "I" },
    { answer: "M" },
    { answer: "E" },
    { answer: "L" },
    { answer: "I" },
    { answer: "N" },
    { answer: "E" },
  ],
  [
    { answer: "S", number: 14 },
    { answer: "I" },
    { answer: "T" },
    { answer: "E" },
    { answer: null, isBlocked: true },
    { answer: "E" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "E" },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: "C" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "D" },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: "S" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "C", number: 15 },
    { answer: "L" },
    { answer: "I" },
    { answer: "C" },
    { answer: "K" },
    { answer: "B" },
    { answer: "A" },
    { answer: "I" },
    { answer: "T" },
    { answer: null, isBlocked: true },
  ],
];

export const CLUES_SOCIAL_HARD: Clue[] = [
  // Across
  {
    number: 1,
    clue: "Alert message on apps",
    answer: "NOTIFICATION",
    startRow: 0,
    startCol: 3,
    direction: "across",
  },
  {
    number: 2,
    clue: "For You Page abbreviation",
    answer: "FYP",
    startRow: 2,
    startCol: 8,
    direction: "across",
  },
  {
    number: 3,
    clue: "Number of views or engagements",
    answer: "IMPRESSIONS",
    startRow: 5,
    startCol: 4,
    direction: "across",
  },
  {
    number: 4,
    clue: "Brand teamwork feature",
    answer: "COLLAB",
    startRow: 7,
    startCol: 8,
    direction: "across",
  },
  {
    number: 5,
    clue: "Click-provoking title style",
    answer: "RAGEBAIT",
    startRow: 9,
    startCol: 8,
    direction: "across",
  },
  {
    number: 6,
    clue: "Chronological content display",
    answer: "TIMELINE",
    startRow: 12,
    startCol: 8,
    direction: "across",
  },
  {
    number: 7,
    clue: "Basic web address",
    answer: "SITE",
    startRow: 13,
    startCol: 0,
    direction: "across",
  },
  {
    number: 8,
    clue: "Deceptive headline to boost clicks",
    answer: "CLICKBAIT",
    startRow: 15,
    startCol: 6,
    direction: "across",
  },

  // Down
  {
    number: 9,
    clue: "Long-form Instagram video format",
    answer: "IGTV",
    startRow: 0,
    startCol: 6,
    direction: "down",
  },
  {
    number: 10,
    clue: "Popular social media personality",
    answer: "INFLUENCER",
    startRow: 0,
    startCol: 8,
    direction: "down",
  },
  {
    number: 11,
    clue: "Response to a comment or post",
    answer: "REPLY",
    startRow: 2,
    startCol: 0,
    direction: "down",
  },
  {
    number: 12,
    clue: "Digital universe concept",
    answer: "METAVERSE",
    startRow: 5,
    startCol: 5,
    direction: "down",
  },
  {
    number: 13,
    clue: "Content measurement tool",
    answer: "ANALYTICS",
    startRow: 7,
    startCol: 1,
    direction: "down",
  },
  {
    number: 14,
    clue: "Short animated image format",
    answer: "GIF",
    startRow: 8,
    startCol: 14,
    direction: "down",
  },
  {
    number: 15,
    clue: "Where you see new content",
    answer: "FEED",
    startRow: 11,
    startCol: 15,
    direction: "down",
  },
  {
    number: 16,
    clue: "Not safe for work content (abbr.)",
    answer: "NSFW",
    startRow: 0,
    startCol: 3,
    direction: "down",
  },
];
