import { Cell, Clue } from "@/types";

export const GRID_SOCIAL_MEDIUM: Cell[][] = [
  [
    { answer: "S", number: 1 },
    { answer: "T", number: 2 },
    { answer: "O" },
    { answer: "R" },
    { answer: "Y" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "E", number: 3 },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: "R" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "M" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: "O", number: 4 },
    { answer: "N" },
    { answer: "L", number: 5 },
    { answer: "I" },
    { answer: "N" },
    { answer: "E" },
    { answer: null, isBlocked: true },
    { answer: "F", number: 6 },
    { answer: "O" },
    { answer: "L" },
    { answer: "L" },
    { answer: "O" },
    { answer: "W" },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: "L" },
    { answer: null, isBlocked: true },
    { answer: "O" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "J" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: "L" },
    { answer: null, isBlocked: true },
    { answer: "G", number: 7 },
    { answer: "R" },
    { answer: "O" },
    { answer: "U" },
    { answer: "P" },
    { answer: null, isBlocked: true },
    { answer: "I" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "P", number: 8 },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "I" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "R", number: 9 },
    { answer: null, isBlocked: true },
    { answer: "O" },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "N" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "S", number: 10 },
    { answer: "T" },
    { answer: "R" },
    { answer: "E" },
    { answer: "A" },
    { answer: "K" },
  ],
  [
    { answer: "S", number: 11 },
    { answer: "A" },
    { answer: "V" },
    { answer: "E" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "I" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "P" },
    { answer: null, isBlocked: true },
    { answer: "E" },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "M", number: 12 },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "G" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "O" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "R", number: 13 },
    { answer: "E" },
    { answer: "E" },
    { answer: "L" },
    { answer: null, isBlocked: true },
    { answer: "N" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "S", number: 14 },
    { answer: "U" },
    { answer: "B", number: 15 },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "M" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "A" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "T" },
    { answer: null, isBlocked: true },
    { answer: "O" },
  ],
  [
    { answer: "F", number: 15 },
    { answer: "I" },
    { answer: "L" },
    { answer: "T" },
    { answer: "E" },
    { answer: "R" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "L" },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "T" },
  ],
  [
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: null, isBlocked: true },
    { answer: "S" },
  ],
];

export const CLUES_SOCIAL_MEDIUM: Clue[] = [
  // Across
  {
    number: 1,
    clue: "Temporary photo or video post on platforms like Instagram and Snapchat",
    answer: "STORY",
    startRow: 0,
    startCol: 0,
    direction: "across",
  },
  {
    number: 4,
    clue: "Connected to the internet or a digital service",
    answer: "ONLINE",
    startRow: 2,
    startCol: 1,
    direction: "across",
  },
  {
    number: 6,
    clue: "Tap this to keep updated with someone’s posts",
    answer: "FOLLOW",
    startRow: 2,
    startCol: 8,
    direction: "across",
  },
  {
    number: 7,
    clue: "A place where members share content around a specific interest",
    answer: "GROUP",
    startRow: 4,
    startCol: 3,
    direction: "across",
  },
  {
    number: 10,
    clue: "A chain of daily snaps between two users",
    answer: "STREAK",
    startRow: 6,
    startCol: 8,
    direction: "across",
  },
  {
    number: 11,
    clue: "Option to keep a post to view later",
    answer: "SAVE",
    startRow: 7,
    startCol: 0,
    direction: "across",
  },
  {
    number: 13,
    clue: "Short video clip, common on Instagram and YouTube",
    answer: "REEL",
    startRow: 9,
    startCol: 3,
    direction: "across",
  },
  {
    number: 14,
    clue: "YouTube button to receive updates from a creator",
    answer: "SUB",
    startRow: 9,
    startCol: 11,
    direction: "across",
  },
  {
    number: 15,
    clue: "Tool to enhance photos by changing brightness or color",
    answer: "FILTER",
    startRow: 11,
    startCol: 0,
    direction: "across",
  },

  // Down
  {
    number: 2,
    clue: "A person who provokes others online just for reactions",
    answer: "TROLL",
    startRow: 0,
    startCol: 1,
    direction: "down",
  },
  {
    number: 3,
    clue: "Small digital icon used to express emotions",
    answer: "EMOJI",
    startRow: 0,
    startCol: 9,
    direction: "down",
  },
  {
    number: 5,
    clue: "Process of accessing your account using a username and password",
    answer: "LOGIN",
    startRow: 2,
    startCol: 3,
    direction: "down",
  },
  {
    number: 8,
    clue: "Old Facebook feature to get someone’s attention",
    answer: "POKE",
    startRow: 4,
    startCol: 13,
    direction: "down",
  },
  {
    number: 9,
    clue: "To share someone else’s post on your timeline",
    answer: "REPOST",
    startRow: 5,
    startCol: 11,
    direction: "down",
  },
  {
    number: 10,
    clue: "Privacy-focused messaging app known for encryption",
    answer: "SIGNAL",
    startRow: 6,
    startCol: 8,
    direction: "down",
  },
  {
    number: 12,
    clue: "Funny image or video that spreads quickly online",
    answer: "MEME",
    startRow: 8,
    startCol: 4,
    direction: "down",
  },
  {
    number: 15,
    clue: "Automated account that posts or interacts without human input",
    answer: "BOTS",
    startRow: 9,
    startCol: 13,
    direction: "down",
  },
];
