import { IndianState } from "@/types";

export const INDIAN_STATES: IndianState[] = [
  { name: "Andhra Pradesh", state_code: "AP" },
  { name: "Arunachal Pradesh", state_code: "AR" },
  { name: "Assam", state_code: "AS" },
  { name: "Bihar", state_code: "BR" },
  { name: "Chhattisgarh", state_code: "CG" },
  { name: "Goa", state_code: "GA" },
  { name: "Gujarat", state_code: "GJ" },
  { name: "Haryana", state_code: "HR" },
  { name: "Himachal Pradesh", state_code: "HP" },
  { name: "Jharkhand", state_code: "JH" },
  { name: "Karnataka", state_code: "KA" },
  { name: "Kerala", state_code: "KL" },
  { name: "Madhya Pradesh", state_code: "MP" },
  { name: "Maharashtra", state_code: "MH" },
  { name: "Manipur", state_code: "MN" },
  { name: "Meghalaya", state_code: "ML" },
  { name: "Mizoram", state_code: "MZ" },
  { name: "Nagaland", state_code: "NL" },
  { name: "Odisha", state_code: "OR" },
  { name: "Punjab", state_code: "PB" },
  { name: "Rajasthan", state_code: "RJ" },
  { name: "Sikkim", state_code: "SK" },
  { name: "Tamil Nadu", state_code: "TN" },
  { name: "Telangana", state_code: "TS" },
  { name: "Tripura", state_code: "TR" },
  { name: "Uttar Pradesh", state_code: "UP" },
  { name: "Uttarakhand", state_code: "UK" },
  { name: "West Bengal", state_code: "WB" },
  { name: "Andaman and Nicobar Islands", state_code: "AN" },
  { name: "Chandigarh", state_code: "CH" },
  { name: "Dadra and Nagar Haveli and Daman and Diu", state_code: "DN" },
  { name: "Delhi", state_code: "DL" },
  { name: "Jammu and Kashmir", state_code: "JK" },
  { name: "Ladakh", state_code: "LA" },
  { name: "Lakshadweep", state_code: "LD" },
  { name: "Puducherry", state_code: "PY" },
];
